### ISSUE TITLE
Thread 'IO Worker #2' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', libcore/option.rs:1008

### ISSUE THREAD

**Issue by danielglauser** [openethereum/openethereum#10075]
- **Parity Ethereum version**: v2.1.10-stable-b47e064f8-20181213/x86_64-macos/rustc1.31.0
- **Operating system**: MacOS
- **Installation**: homebrew
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

Fresh install of Parity. Fresh DB directory. Ran like this:
`parity --db-path /Volumes/Extreme\ SSD/parity-latest --no-warp --no-ancient-blocks --no-serve-light --max-peers 250 --snapshot-peers 50 --min-peers 50 --mode active --tracing off --pruning fast --db-compaction ssd --cache-size 10000`

Stuck for a long time (over 10 hours) on block #263023

```
2018-12-16 11:45:52  Syncing  #263023 0x3f8e…b4ca     0.00 blk/s    0.0 tx/s    0 Mgas/s      0+    0 Qed   #263062   26/50 peers   134 MiB chain 66 MiB db 0 bytes queue 110 MiB sync  RPC:  0 conn,    0 req/s,    0 µs
2018-12-16 11:46:22  Syncing  #263023 0x3f8e…b4ca     0.00 blk/s    0.0 tx/s    0 Mgas/s      0+    0 Qed   #263062   22/50 peers   134 MiB chain 66 MiB db 0 bytes queue 110 MiB sync  RPC:  0 conn,    0 req/s,    0 µs


====================

stack backtrace:
   0:        0x10cc1e7ae - <unknown>
   1:        0x10cc1f57c - <unknown>
   2:        0x10cc1f5fd - <unknown>
   3:        0x10cc1e08b - <unknown>
   4:        0x10b1d1caa - <unknown>
   5:        0x10cc8daf8 - <unknown>
   6:        0x10cc8d60c - <unknown>
   7:        0x10cc8d4f8 - <unknown>
   8:        0x10ccd1371 - <unknown>
   9:        0x10ccd13e8 - <unknown>
  10:        0x10c0674c5 - <unknown>
  11:        0x10c066dea - <unknown>
  12:        0x10bf07ff2 - <unknown>
  13:        0x10bdfef55 - <unknown>
  14:        0x10c0816ec - <unknown>
  15:        0x10be256cc - <unknown>
  16:        0x10c06311a - <unknown>
  17:        0x10c09f029 - <unknown>
  18:        0x10bb644e8 - <unknown>
  19:        0x10bb5bb6c - <unknown>
  20:        0x10bb42a59 - <unknown>
  21:        0x10bb42c64 - <unknown>
  22:        0x10cc992ae - <unknown>
  23:        0x10bb56cc2 - <unknown>
  24:        0x10cc8a3a7 - <unknown>
  25:        0x10cc6e5a8 - <unknown>
  26:     0x7fff7e865304 - __pthread_body
  27:     0x7fff7e86826e - __pthread_start

Thread 'IO Worker #2' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', libcore/option.rs:1008

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new
```

**Comment by danielglauser** [comment]
Looking to sync from block 4034051 to the most recent. Happy to try some experiments if that is helpful.

**Comment by joshua-mir** [comment]
Are you trying to sync *only* those blocks (as --no-ancient-blocks would imply) or sync from genesis (as --no-warp implies)?

**Comment by joshua-mir** [comment]
@shouvik2016 could you please share what flags/config you are running with?

**Comment by adria0** [comment]
Closing the issue due to its stale state
