### ISSUE TITLE
ancient block sync panic: parent total difficulty always supplied for first block in chunk. only first block can have missing parent.

### ISSUE THREAD

**Issue by 5chdn** [openethereum/openethereum#10127]
- **Parity Ethereum version**: 2.3.0 nightly @ 515108714
- **Operating system**: Arch Linux
- **Installation**: built from source (PR #10123 - but should be unrelated)
- **Fully synchronized**: no
- **Network**: classic
- **Restarted**: yes

```
❯ ./target/release/parity --chain classic --ports-shift 200 --reserved-peers ~/Desktop/classic
2019-01-03 12:15:14  Starting Parity-Ethereum/v2.3.0-nightly-515108714-20190103/x86_64-linux-gnu/rustc1.31.1
2019-01-03 12:15:14  Keys path /home/user/.local/share/io.parity.ethereum/keys/classic
2019-01-03 12:15:14  DB path /home/user/.local/share/io.parity.ethereum/chains/classic/db/906a34e69aec8c0d
2019-01-03 12:15:14  State DB configuration: fast
2019-01-03 12:15:14  Operating mode: active
2019-01-03 12:15:14  Configured for Ethereum Classic using Ethash engine
2019-01-03 12:15:21  Public node URL: enode://8dc97200ad854694b5c3ddfc9759907bcc1a7a817f750c0e80785dffab23d330428d04818e9540d2bbd9bc8294b0d2ff08b5975308418ea81d8c49c6faf091a3@192.168.43.131:30503
2019-01-03 12:15:24  Imported #7232868 0x5ab7…ef45 (5 txs, 0.26 Mgas, 38 ms, 1.16 KiB)
2019-01-03 12:15:29  Error importing ancient block: Block error (Seal element out of bounds: Expected 0xe0d0…bc7a, found 0x900b…b42c)


====================

stack backtrace:
   0:     0x5642c484c7cd - backtrace::backtrace::trace::h6a895d5d279a8d2f
   1:     0x5642c484b9e2 - <backtrace::capture::Backtrace as core::default::Default>::default::h03a8d770395d927e
   2:     0x5642c484ba59 - backtrace::capture::Backtrace::new::h2eb1c11c92f206be
   3:     0x5642c484ab96 - panic_hook::gen_panic_msg::hf38c962aa96f7e35
   4:     0x5642c3013e88 - panic_hook::set_with::{{closure}}::h2adb1ed3fd612fa1
   5:     0x5642c48c00c6 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   6:     0x5642c48bfc11 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   7:     0x5642c48bfaf5 - rust_begin_unwind
                        at libstd/panicking.rs:325
   8:     0x5642c490968c - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   9:     0x5642c4909702 - core::option::expect_failed::hb2b5d5a53baf7df0
                        at libcore/option.rs:1008
  10:     0x5642c3de5988 - ethcore::blockchain::blockchain::BlockChain::insert_unordered_block::hb4d97bf4def001f0
  11:     0x5642c3d14ecb - ethcore::client::client::Importer::import_old_block::h78b38d0110f7a451
  12:     0x5642c3f5d065 - ethcore::client::client::IoChannelQueue::queue::{{closure}}::ha53ae52d5a9f1a7a
  13:     0x5642c3858768 - <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message::h3d6d3c251821b0d8
  14:     0x5642c385a1d2 - ethcore_io::worker::Worker::do_work::h7e123e04959c9851
  15:     0x5642c386d206 - ethcore_io::worker::Worker::new::{{closure}}::{{closure}}::h11b63da778530a6c
  16:     0x5642c387109c - <futures::future::loop_fn::LoopFn<A, F> as futures::future::Future>::poll::ha6c40f99a073607c
  17:     0x5642c385c07c - futures::task_impl::std::set::hde85d0c9c44e3423
  18:     0x5642c3883943 - <std::thread::local::LocalKey<T>>::with::h6deb5472439fb4cd
  19:     0x5642c3870766 - <tokio_current_thread::Entered<'a, P>>::block_on::he478205605796353
  20:     0x5642c3883e71 - <std::thread::local::LocalKey<T>>::with::he01f4da0b857073e
  21:     0x5642c38833d8 - <std::thread::local::LocalKey<T>>::with::h3567b55292e4819c
  22:     0x5642c3883774 - <std::thread::local::LocalKey<T>>::with::h4752879c5050ef10
  23:     0x5642c388423b - <std::thread::local::LocalKey<T>>::with::he2b849aa90725aef
  24:     0x5642c386c721 - tokio::runtime::current_thread::block_on_all::h3c9e77e459bfe6cc
  25:     0x5642c386d834 - std::sys_common::backtrace::__rust_begin_short_backtrace::h18175a644369d317
  26:     0x5642c3869686 - std::panicking::try::do_call::hc026b6b35bb3cf9b
  27:     0x5642c48d22a9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  28:     0x5642c3874c97 - <F as alloc::boxed::FnBox<A>>::call_box::h8252ea05682a9de0
  29:     0x5642c48bc55d - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9d902c911a417e39
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h44127e03e78ca137
                        at libstd/sys_common/thread.rs:24
  30:     0x5642c48a7115 - std::sys::unix::thread::Thread::new::thread_start::h8f17b97f2223146c
                        at libstd/sys/unix/thread.rs:90
  31:     0x7f30574b0a9c - start_thread
  32:     0x7f30573c4b22 - clone
  33:                0x0 - <unknown>

Thread 'IO Worker #0' panicked at 'parent total difficulty always supplied for first block in chunk. only first block can have missing parent; qed', libcore/option.rs:1008

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new

2019-01-03 12:15:29  Finishing work, please wait...


====================

stack backtrace:
   0:     0x5642c484c7cd - backtrace::backtrace::trace::h6a895d5d279a8d2f
   1:     0x5642c484b9e2 - <backtrace::capture::Backtrace as core::default::Default>::default::h03a8d770395d927e
   2:     0x5642c484ba59 - backtrace::capture::Backtrace::new::h2eb1c11c92f206be
   3:     0x5642c484ab96 - panic_hook::gen_panic_msg::hf38c962aa96f7e35
   4:     0x5642c3013e88 - panic_hook::set_with::{{closure}}::h2adb1ed3fd612fa1
   5:     0x5642c48c00c6 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   6:     0x5642c48bfc11 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   7:     0x5642c48bfaf5 - rust_begin_unwind
                        at libstd/panicking.rs:325
   8:     0x5642c490968c - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   9:     0x5642c4909702 - core::option::expect_failed::hb2b5d5a53baf7df0
                        at libcore/option.rs:1008
  10:     0x5642c3de5988 - ethcore::blockchain::blockchain::BlockChain::insert_unordered_block::hb4d97bf4def001f0
  11:     0x5642c3d14ecb - ethcore::client::client::Importer::import_old_block::h78b38d0110f7a451
  12:     0x5642c3f5d065 - ethcore::client::client::IoChannelQueue::queue::{{closure}}::ha53ae52d5a9f1a7a
  13:     0x5642c3858768 - <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message::h3d6d3c251821b0d8
  14:     0x5642c385a1d2 - ethcore_io::worker::Worker::do_work::h7e123e04959c9851
  15:     0x5642c386d206 - ethcore_io::worker::Worker::new::{{closure}}::{{closure}}::h11b63da778530a6c
  16:     0x5642c387109c - <futures::future::loop_fn::LoopFn<A, F> as futures::future::Future>::poll::ha6c40f99a073607c
  17:     0x5642c385c07c - futures::task_impl::std::set::hde85d0c9c44e3423
  18:     0x5642c3883943 - <std::thread::local::LocalKey<T>>::with::h6deb5472439fb4cd
  19:     0x5642c3870766 - <tokio_current_thread::Entered<'a, P>>::block_on::he478205605796353
  20:     0x5642c3883e71 - <std::thread::local::LocalKey<T>>::with::he01f4da0b857073e
  21:     0x5642c38833d8 - <std::thread::local::LocalKey<T>>::with::h3567b55292e4819c
  22:     0x5642c3883774 - <std::thread::local::LocalKey<T>>::with::h4752879c5050ef10
  23:     0x5642c388423b - <std::thread::local::LocalKey<T>>::with::he2b849aa90725aef
  24:     0x5642c386c721 - tokio::runtime::current_thread::block_on_all::h3c9e77e459bfe6cc
  25:     0x5642c386d834 - std::sys_common::backtrace::__rust_begin_short_backtrace::h18175a644369d317
  26:     0x5642c3869686 - std::panicking::try::do_call::hc026b6b35bb3cf9b
  27:     0x5642c48d22a9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  28:     0x5642c3874c97 - <F as alloc::boxed::FnBox<A>>::call_box::h8252ea05682a9de0
  29:     0x5642c48bc55d - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9d902c911a417e39
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h44127e03e78ca137
                        at libstd/sys_common/thread.rs:24
  30:     0x5642c48a7115 - std::sys::unix::thread::Thread::new::thread_start::h8f17b97f2223146c
                        at libstd/sys/unix/thread.rs:90
  31:     0x7f30574b0a9c - start_thread
  32:     0x7f30573c4b22 - clone
  33:                0x0 - <unknown>

Thread 'IO Worker #3' panicked at 'parent total difficulty always supplied for first block in chunk. only first block can have missing parent; qed', libcore/option.rs:1008

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new



====================

stack backtrace:
   0:     0x5642c484c7cd - backtrace::backtrace::trace::h6a895d5d279a8d2f
   1:     0x5642c484b9e2 - <backtrace::capture::Backtrace as core::default::Default>::default::h03a8d770395d927e
   2:     0x5642c484ba59 - backtrace::capture::Backtrace::new::h2eb1c11c92f206be
   3:     0x5642c484ab96 - panic_hook::gen_panic_msg::hf38c962aa96f7e35
   4:     0x5642c3013e88 - panic_hook::set_with::{{closure}}::h2adb1ed3fd612fa1
   5:     0x5642c48c00c6 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   6:     0x5642c48bfc11 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   7:     0x5642c48bfaf5 - rust_begin_unwind
                        at libstd/panicking.rs:325
   8:     0x5642c490968c - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   9:     0x5642c4909702 - core::option::expect_failed::hb2b5d5a53baf7df0
                        at libcore/option.rs:1008
  10:     0x5642c3de5988 - ethcore::blockchain::blockchain::BlockChain::insert_unordered_block::hb4d97bf4def001f0
  11:     0x5642c3d14ecb - ethcore::client::client::Importer::import_old_block::h78b38d0110f7a451
  12:     0x5642c3f5d065 - ethcore::client::client::IoChannelQueue::queue::{{closure}}::ha53ae52d5a9f1a7a
  13:     0x5642c3858768 - <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message::h3d6d3c251821b0d8
  14:     0x5642c385a1d2 - ethcore_io::worker::Worker::do_work::h7e123e04959c9851
  15:     0x5642c386d206 - ethcore_io::worker::Worker::new::{{closure}}::{{closure}}::h11b63da778530a6c
  16:     0x5642c387109c - <futures::future::loop_fn::LoopFn<A, F> as futures::future::Future>::poll::ha6c40f99a073607c
  17:     0x5642c385c07c - futures::task_impl::std::set::hde85d0c9c44e3423
  18:     0x5642c3883943 - <std::thread::local::LocalKey<T>>::with::h6deb5472439fb4cd
  19:     0x5642c3870766 - <tokio_current_thread::Entered<'a, P>>::block_on::he478205605796353
  20:     0x5642c3883e71 - <std::thread::local::LocalKey<T>>::with::he01f4da0b857073e
  21:     0x5642c38833d8 - <std::thread::local::LocalKey<T>>::with::h3567b55292e4819c
  22:     0x5642c3883774 - <std::thread::local::LocalKey<T>>::with::h4752879c5050ef10
  23:     0x5642c388423b - <std::thread::local::LocalKey<T>>::with::he2b849aa90725aef
  24:     0x5642c386c721 - tokio::runtime::current_thread::block_on_all::h3c9e77e459bfe6cc
  25:     0x5642c386d834 - std::sys_common::backtrace::__rust_begin_short_backtrace::h18175a644369d317
  26:     0x5642c3869686 - std::panicking::try::do_call::hc026b6b35bb3cf9b
  27:     0x5642c48d22a9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  28:     0x5642c3874c97 - <F as alloc::boxed::FnBox<A>>::call_box::h8252ea05682a9de0
  29:     0x5642c48bc55d - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9d902c911a417e39
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h44127e03e78ca137
                        at libstd/sys_common/thread.rs:24
  30:     0x5642c48a7115 - std::sys::unix::thread::Thread::new::thread_start::h8f17b97f2223146c
                        at libstd/sys/unix/thread.rs:90
  31:     0x7f30574b0a9c - start_thread
  32:     0x7f30573c4b22 - clone
  33:                0x0 - <unknown>

Thread 'IO Worker #2' panicked at 'parent total difficulty always supplied for first block in chunk. only first block can have missing parent; qed', libcore/option.rs:1008

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new



====================

stack backtrace:
   0:     0x5642c484c7cd - backtrace::backtrace::trace::h6a895d5d279a8d2f
   1:     0x5642c484b9e2 - <backtrace::capture::Backtrace as core::default::Default>::default::h03a8d770395d927e
   2:     0x5642c484ba59 - backtrace::capture::Backtrace::new::h2eb1c11c92f206be
   3:     0x5642c484ab96 - panic_hook::gen_panic_msg::hf38c962aa96f7e35
   4:     0x5642c3013e88 - panic_hook::set_with::{{closure}}::h2adb1ed3fd612fa1
   5:     0x5642c48c00c6 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   6:     0x5642c48bfc11 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   7:     0x5642c48bfaf5 - rust_begin_unwind
                        at libstd/panicking.rs:325
   8:     0x5642c490968c - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   9:     0x5642c4909702 - core::option::expect_failed::hb2b5d5a53baf7df0
                        at libcore/option.rs:1008
  10:     0x5642c3de5988 - ethcore::blockchain::blockchain::BlockChain::insert_unordered_block::hb4d97bf4def001f0
  11:     0x5642c3d14ecb - ethcore::client::client::Importer::import_old_block::h78b38d0110f7a451
  12:     0x5642c3f5d065 - ethcore::client::client::IoChannelQueue::queue::{{closure}}::ha53ae52d5a9f1a7a
  13:     0x5642c3858768 - <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message::h3d6d3c251821b0d8
  14:     0x5642c385a1d2 - ethcore_io::worker::Worker::do_work::h7e123e04959c9851
  15:     0x5642c386d206 - ethcore_io::worker::Worker::new::{{closure}}::{{closure}}::h11b63da778530a6c
  16:     0x5642c387109c - <futures::future::loop_fn::LoopFn<A, F> as futures::future::Future>::poll::ha6c40f99a073607c
  17:     0x5642c385c07c - futures::task_impl::std::set::hde85d0c9c44e3423
  18:     0x5642c3883943 - <std::thread::local::LocalKey<T>>::with::h6deb5472439fb4cd
  19:     0x5642c3870766 - <tokio_current_thread::Entered<'a, P>>::block_on::he478205605796353
  20:     0x5642c3883e71 - <std::thread::local::LocalKey<T>>::with::he01f4da0b857073e
  21:     0x5642c38833d8 - <std::thread::local::LocalKey<T>>::with::h3567b55292e4819c
  22:     0x5642c3883774 - <std::thread::local::LocalKey<T>>::with::h4752879c5050ef10
  23:     0x5642c388423b - <std::thread::local::LocalKey<T>>::with::he2b849aa90725aef
  24:     0x5642c386c721 - tokio::runtime::current_thread::block_on_all::h3c9e77e459bfe6cc
  25:     0x5642c386d834 - std::sys_common::backtrace::__rust_begin_short_backtrace::h18175a644369d317
  26:     0x5642c3869686 - std::panicking::try::do_call::hc026b6b35bb3cf9b
  27:     0x5642c48d22a9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  28:     0x5642c3874c97 - <F as alloc::boxed::FnBox<A>>::call_box::h8252ea05682a9de0
  29:     0x5642c48bc55d - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9d902c911a417e39
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h44127e03e78ca137
                        at libstd/sys_common/thread.rs:24
  30:     0x5642c48a7115 - std::sys::unix::thread::Thread::new::thread_start::h8f17b97f2223146c
                        at libstd/sys/unix/thread.rs:90
  31:     0x7f30574b0a9c - start_thread
  32:     0x7f30573c4b22 - clone
  33:                0x0 - <unknown>

Thread 'IO Worker #1' panicked at 'parent total difficulty always supplied for first block in chunk. only first block can have missing parent; qed', libcore/option.rs:1008

```

**Comment by adria0** [comment]
Closing the issue due to its stale state
