### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by ltfschoen** [openethereum/openethereum#10136]
- **Parity Ethereum version**: Parity-Ethereum/v2.1.10-stable-b47e064f8-20181213/x86_64-macos/rustc1.31.0
- **Operating system**: MacOS
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: all (i.e. foundation, ropsten, kovan)
- **Restarted**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I was running Parity Ethereum v2.1.9 stable without any issues.
Then I updated to v2.1.10 stable.
When I try to connect to any chain I get error:
```
scon @ ~/code/src/paritytech/parity-ethereum - [stable] $ ./target/release/parity --chain kovan --light --ws-origins=*
2019-01-05 20:26:46  Starting Parity-Ethereum/v2.1.10-stable-b47e064f8-20181213/x86_64-macos/rustc1.31.0
2019-01-05 20:26:46  Keys path /Users/scon/Library/Application Support/io.parity.ethereum/keys/kovan
2019-01-05 20:26:46  DB path /Users/scon/Library/Application Support/io.parity.ethereum/chains_light/kovan/db/9bf388941c25ea98
2019-01-05 20:26:46  Running in experimental Light Client mode.
2019-01-05 20:26:46  Debug API is not available in light client mode.
2019-01-05 20:26:46  Debug API is not available in light client mode.
2019-01-05 20:26:51  Public node URL: enode://25d97eab21b251a819a21cf914ded0493786fa4bc12c5906c455b2a7060d4d00a03c669286ce504438bdecb39942f2dc6e431231d0b53fc9655cc776b12f69cd@192.168.43.40:30303
2019-01-05 20:26:51  Syncing #9868393 0xa590…3095     0.0 hdr/s      0+    0 Qed   5/50 peers   664 bytes cache 0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs


====================

stack backtrace:
   0:        0x10588060e - backtrace::backtrace::trace::h631f5ced4778926c
   1:        0x1058813dc - <backtrace::capture::Backtrace as core::default::Default>::default::h2150cb28c2973a81
   2:        0x10588145d - backtrace::capture::Backtrace::new::h8f49e8fcc1595e72
   3:        0x10588011b - panic_hook::gen_panic_msg::h5301cd57ed1de95d
   4:        0x103db247a - panic_hook::set_with::{{closure}}::h01721e963db37c09
   5:        0x1058ef998 - std::panicking::rust_panic_with_hook::h11860e91fb60d90b
   6:        0x1058ef4ac - std::panicking::continue_panic_fmt::h28d8e12e50184e99
   7:        0x1058ef398 - _rust_begin_unwind
   8:        0x105933211 - core::panicking::panic_fmt::hc0099dc0d85edf22
   9:        0x10487b09d - core::result::unwrap_failed::hd9c1f4a49b9115b8
  10:        0x104865ecc - <ethcore_network_devp2p::host::Host as ethcore_io::IoHandler<ethcore_network::NetworkIoMessage>>::message::h30bad8df1c8e94f3
  11:        0x10488d5ec - ethcore_io::worker::Worker::work_loop::h6dbfdfca997d75a8
  12:        0x104834cc9 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd6b6e1dda62bb774
  13:        0x10488df64 - std::panicking::try::do_call::h586e90235893e4b0
  14:        0x1058fb14e - ___rust_maybe_catch_panic
  15:        0x104837ee2 - <F as alloc::boxed::FnBox<A>>::call_box::h2a2f451b20de84b3
  16:        0x1058ec247 - std::sys_common::thread::start_thread::h24d08beb3985b9d2
  17:        0x1058d0448 - std::sys::unix::thread::Thread::new::thread_start::h9ca5dbae56c6730a
  18:     0x7fff6775a33c - __pthread_body
  19:     0x7fff6775d2a6 - __pthread_start

Thread 'IO Worker #0' panicked at 'Error binding UDP socket: Os { code: 48, kind: AddrInUse, message: "Address already in use" }', libcore/result.rs:1009

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new
```

I've killed `webpack-serve` processes, and ran `ps aux` and killed the following Parity-related processes, but i still get the error.
```
scon             58345   0.3  0.1  5101800   7880   ??  S    Fri07PM   5:55.25 node /Users/scon/code/src/paritytech/fether/node_modules/.bin/jest --json --useStderr --outputFile /var/folder
scon             77774   0.3  0.0  4714144    556   ??  S    11Dec18  42:11.47 node /Users/scon/code/src/polkadot-js/api/node_modules/.bin/jest --json --useStderr --outputFile /var/folders/
```

I've since restarted the computer and recompiling to see if that fixes the issue.

Duplicate of https://github.com/paritytech/parity-ethereum/issues/2164

**Comment by ltfschoen** [comment]
An hour later and it happened again.
I'd just been stopping and starting either `./target/release/parity --chain kovan --light --ws-origins=*` or `./target/release/parity --chain kovan --ws-origins=*` and running Fether with `yarn; yarn build; yarn start`
:
```
scon @ ~/code/src/paritytech/parity-ethereum - [stable] $ ./target/release/parity --chain kovan --ws-origins=*
2019-01-05 22:29:14  Starting Parity-Ethereum/v2.1.10-stable-b47e064f8-20181213/x86_64-macos/rustc1.31.0
2019-01-05 22:29:14  Keys path /Users/scon/Library/Application Support/io.parity.ethereum/keys/kovan
2019-01-05 22:29:14  DB path /Users/scon/Library/Application Support/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98
2019-01-05 22:29:14  State DB configuration: fast
2019-01-05 22:29:14  Operating mode: active
2019-01-05 22:29:14  Configured for Kovan using AuthorityRound engine
2019-01-05 22:29:20  Public node URL: enode://25d97eab21b251a819a21cf914ded0493786fa4bc12c5906c455b2a7060d4d00a03c669286ce504438bdecb39942f2dc6e431231d0b53fc9655cc776b12f69cd@192.168.43.40:30303


====================

stack backtrace:
   0:        0x10688160e - backtrace::backtrace::trace::h631f5ced4778926c
   1:        0x1068823dc - <backtrace::capture::Backtrace as core::default::Default>::default::h2150cb28c2973a81
   2:        0x10688245d - backtrace::capture::Backtrace::new::h8f49e8fcc1595e72
   3:        0x10688111b - panic_hook::gen_panic_msg::h5301cd57ed1de95d
   4:        0x104db347a - panic_hook::set_with::{{closure}}::h01721e963db37c09
   5:        0x1068f0998 - std::panicking::rust_panic_with_hook::h11860e91fb60d90b
   6:        0x1068f04ac - std::panicking::continue_panic_fmt::h28d8e12e50184e99
   7:        0x1068f0398 - _rust_begin_unwind
   8:        0x106934211 - core::panicking::panic_fmt::hc0099dc0d85edf22
   9:        0x10587c09d - core::result::unwrap_failed::hd9c1f4a49b9115b8
  10:        0x105866ecc - <ethcore_network_devp2p::host::Host as ethcore_io::IoHandler<ethcore_network::NetworkIoMessage>>::message::h30bad8df1c8e94f3
  11:        0x10588e5ec - ethcore_io::worker::Worker::work_loop::h6dbfdfca997d75a8
  12:        0x105835cc9 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd6b6e1dda62bb774
  13:        0x10588ef64 - std::panicking::try::do_call::h586e90235893e4b0
  14:        0x1068fc14e - ___rust_maybe_catch_panic
  15:        0x105838ee2 - <F as alloc::boxed::FnBox<A>>::call_box::h2a2f451b20de84b3
  16:        0x1068ed247 - std::sys_common::thread::start_thread::h24d08beb3985b9d2
  17:        0x1068d1448 - std::sys::unix::thread::Thread::new::thread_start::h9ca5dbae56c6730a
  18:     0x7fff6325b33c - __pthread_body
  19:     0x7fff6325e2a6 - __pthread_start

Thread 'IO Worker #2' panicked at 'Error binding UDP socket: Os { code: 48, kind: AddrInUse, message: "Address already in use" }', libcore/result.rs:1009

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new
```

**Comment by 5chdn** [comment]
Shouldn't panic :+1:

**Comment by ltfschoen** [comment]
The only annoyance on macOS is having to restart the computer and having to change back into the last directory I was using in all the terminal tabs I was using, but fortunately it remembers my history of commands

**Comment by adria0** [comment]
Closing the issue due to its stale state
