### ISSUE TITLE
Bug found at version 3.10

### ISSUE THREAD

**Issue by liuzhiyangGDM** [openethereum/openethereum#103]
_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: 0.0.0
- **Operating system**: Windows / MacOS / Linux
- **Installation**: homebrew / one-line installer / built from source
- **Fully synchronized**: no / yes
- **Network**: ethereum / ropsten / kovan / ...
- **Restarted**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

2020-11-17 02:42:27 UTC Syncing #11272475 0x541b…3be5     0.55 blk/s  110.6 tx/s    6.8 Mgas/s      0+   11 Qed  #11272774   25/25 peers      5 MiB chain    1 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2020-11-17 02:42:32 UTC Syncing #11272475 0x541b…3be5     1.00 blk/s  116.2 tx/s    9.9 Mgas/s      0+   11 Qed  #11272774   24/25 peers      6 MiB chain    1 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2020-11-17 02:42:37 UTC Syncing #11272475 0x541b…3be5     1.00 blk/s  183.0 tx/s   12.5 Mgas/s      0+   11 Qed  #11272774   25/25 peers      7 MiB chain    1 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2020-11-17 02:42:37 UTC Panic occured, see stderr for details

====================

stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>

Thread 'IO Worker #2' panicked at 'State root of best block header always valid.: InvalidStateRoot(0x2acea991e7c1ed3e5f8eb807bc48da5117e525ee0d2c8a9a2a7e702d0207b3d6)', ethcore/src/client/client.rs:1179

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new

2020-11-17 02:42:37 UTC Finishing work, please wait...
2020-11-17 02:42:37 UTC Panic occured, see stderr for details

====================

stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>

Thread 'IO Worker #0' panicked at 'State root of best block header always valid.: InvalidStateRoot(0x2acea991e7c1ed3e5f8eb807bc48da5117e525ee0d2c8a9a2a7e702d0207b3d6)', ethcore/src/client/client.rs:1179

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new

Error: 1

**Comment by palkeo** [comment]
What is your rustc compiler version? I think this is possibly related to #120

**Comment by rakita** [comment]
duplicate for #69, fix is made here: https://github.com/openethereum/openethereum/pull/149
