### ISSUE TITLE
Thread 'IO Worker #1' panicked at 'called Option::unwrap() on a None value

### ISSUE THREAD

**Issue by foxban** [openethereum/openethereum#10450]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.3.5
- **Operating system**:  Linux
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: ethereum 
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

====================

stack backtrace:
   0:     0x55cc6a1ffb3d - <no info>
   1:     0x55cc6a1fec62 - <no info>
   2:     0x55cc6a1fde16 - <no info>
   3:     0x55cc689ce228 - <no info>
   4:     0x55cc6a270319 - <no info>
   5:     0x55cc6a26fdc1 - <no info>
   6:     0x55cc6a26fca5 - <no info>
   7:     0x55cc6a28d91c - <no info>
   8:     0x55cc6a28d84b - <no info>
   9:     0x55cc6a286e18 - <no info>
  10:     0x55cc6948be47 - <no info>
  11:     0x55cc6a27a95d - <no info>
  12:     0x7f5282cb06b9 - <no info>
  13:     0x7f52827d041c - <no info>
  14:                0x0 - <no info>

Thread 'IO Worker #1' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:355

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new

fatal runtime error: failed to initiate panic, error 5

**Comment by joshua-mir** [comment]
Can you please share some earlier logs?

**Comment by foxban** [comment]
> Can you please share some earlier logs?

the executing command is as follows:

`/usr/bin/parity --tracing on --pruning archive --datadir=/data01/parity --cache-size=2000 --db-compaction hdd --auto-update=none
`
after parity is launched, its memory usage grows fast, and serveral minutes later, exceeds 3GB and triggered the system's overcommit mechanism.

maybe it's memory leak related?

```
Option '--datadir' is deprecated. Please use '--base-path' instead.
2019-03-06 17:09:54  Starting Parity-Ethereum/v2.3.5-stable-ebd0fd0-20190227/x86_64-linux-gnu/rustc1.32.0
2019-03-06 17:09:54  Keys path /data01/parity/keys/ethereum
2019-03-06 17:09:54  DB path /data01/parity/chains/ethereum/db/906a34e69aec8c0d
2019-03-06 17:09:54  State DB configuration: archive +Trace
2019-03-06 17:09:54  Operating mode: active
2019-03-06 17:09:54  Warning: Warp Sync is disabled because tracing is turned on.
2019-03-06 17:09:56  Configured for Ethereum using Ethash engine
2019-03-06 17:09:57  Removed existing file '/data01/parity/jsonrpc.ipc'.
2019-03-06 17:09:58  Updated conversion rate to Ξ1 = US$137.77 (34564160 wei/gas)
2019-03-06 17:10:02  Public node URL: enode://e18b6320cdd573dafecfca1a7ba3c696e77ab3434c93c86d2c2c0a342b8e89f5c7f7d5a6c8caafab898d020582ba799a6deb3efaa52cb65a80c0a7623326814b@172.21.0.2:30303
2019-03-06 17:10:02  Syncing #7314840 0x7e11…debb     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    5 Qed  #7314847   12/25 peers    151 KiB chain  138 KiB db  470 KiB queue   41 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-03-06 17:10:07  Syncing #7314840 0x7e11…debb     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    6 Qed  #7314848   14/25 peers    363 KiB chain  180 KiB db  554 KiB queue   42 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-03-06 17:10:12  Syncing #7314841 0x31eb…6259     0.20 blk/s   12.4 tx/s    1.4 Mgas/s      0+    6 Qed  #7314848   15/25 peers    370 KiB chain  462 KiB db  554 KiB queue   42 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-03-06 17:10:42    20/25 peers      2 MiB chain    2 MiB db  113 KiB queue   42 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-03-06 17:11:02  Syncing #7314847 0x0b0a…4acc     0.10 blk/s   10.3 tx/s    0.8 Mgas/s      0+    4 Qed  #7314852   21/25 peers     12 MiB chain    2 MiB db  271 KiB queue   42 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-03-06 17:12:06  Imported #7314853 0xf8f2…5b3e (98 txs, 4.77 Mgas, 4029 ms, 16.68 KiB)
2019-03-06 17:12:53  Imported #7314854 0x0518…b08a (165 txs, 7.19 Mgas, 7399 ms, 24.79 KiB)
2019-03-06 17:13:20     5/25 peers     16 MiB chain    3 MiB db  0 bytes queue   42 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-03-06 17:13:20     5/25 peers     16 MiB chain    3 MiB db  0 bytes queue   42 KiB sync  RPC:  0 conn,    0 req/s,    0 µs


====================

stack backtrace:
   0:     0x55c810a68b3d - <no info>
   1:     0x55c810a67c62 - <no info>
   2:     0x55c810a66e16 - <no info>
   3:     0x55c80f237228 - <no info>
   4:     0x55c810ad9319 - <no info>
   5:     0x55c810ad8dc1 - <no info>
   6:     0x55c810ad8ca5 - <no info>
   7:     0x55c810af691c - <no info>
   8:     0x55c81007b689 - <no info>
   9:     0x55c810181af3 - <no info>
  10:     0x55c80fa7d1a0 - <no info>
  11:     0x55c81005eeb9 - <no info>
  12:     0x55c80ffbf488 - <no info>
  13:     0x55c80ffc16fc - <no info>
  14:     0x55c80fee33aa - <no info>
  15:     0x55c810171c5d - <no info>
  16:     0x55c810aefdc9 - <no info>
  17:     0x55c8100ae10e - <no info>
  18:     0x55c810ae395d - <no info>
  19:     0x7fd5b2cc46b9 - <no info>
  20:     0x7fd5b27e441c - <no info>
  21:                0x0 - <no info>

Thread 'Verifier #1' panicked at 'DB flush failed.: Custom { kind: Other, error: StringError("Database write failure. Running low on memory perhaps?") }', src/libcore/result.rs:1009
```

**Comment by foxban** [comment]
following is another error printed on the same machine.

```
Option '--datadir' is deprecated. Please use '--base-path' instead.
2019-03-06 17:16:28  Starting Parity-Ethereum/v2.3.5-stable-ebd0fd0-20190227/x86_64-linux-gnu/rustc1.32.0
2019-03-06 17:16:28  Keys path /data01/parity/keys/ethereum
2019-03-06 17:16:28  DB path /data01/parity/chains/ethereum/db/906a34e69aec8c0d
2019-03-06 17:16:28  State DB configuration: archive +Trace
2019-03-06 17:16:28  Operating mode: active
2019-03-06 17:16:28  Warning: Warp Sync is disabled because tracing is turned on.
2019-03-06 17:16:30  Configured for Ethereum using Ethash engine
2019-03-06 17:16:31  Removed existing file '/data01/parity/jsonrpc.ipc'.
2019-03-06 17:16:32  Updated conversion rate to Ξ1 = US$137.85 (34544100 wei/gas)
2019-03-06 17:16:36  Public node URL: enode://e18b6320cdd573dafecfca1a7ba3c696e77ab3434c93c86d2c2c0a342b8e89f5c7f7d5a6c8caafab898d020582ba799a6deb3efaa52cb65a80c0a7623326814b@172.21.0.2:30303
2019-03-06 17:16:42  Imported #7314877 0xa9d0…e5fb (103 txs, 4.75 Mgas, 4767 ms, 17.41 KiB)
2019-03-06 17:17:47  Imported #7314879 0x580a…a829 (84 txs, 2.54 Mgas, 2540 ms, 12.73 KiB)
2019-03-06 17:19:04    23/25 peers      4 MiB chain    2 MiB db  0 bytes queue   41 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-03-06 17:19:12  Imported #7314883 0xd294…4bd3 (237 txs, 8.00 Mgas, 23256 ms, 34.80 KiB) + another 2 block(s) containing 367 tx(s)
2019-03-06 17:19:58    22/25 peers      5 MiB chain    2 MiB db  0 bytes queue   41 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-03-06 17:19:58  Block import failed for #7314885 (0xb108…e5de): Parent not found (0xbd37…4f2c)
2019-03-06 17:19:58
Bad block detected: Error(Msg("Parent not found"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
RLP: f97176f90215a0bd37363699d20d9c32350149c64f64c8f78311e49dc06a92b11e2b8943454f2ca00bf92ae00ec393ec165c645622039ae4032a3a3dd00cb2207acff618f4f057c294829bd824b016326a401d083b33d092293333a830a0aff6cf771aea323b371dc57de3d6c462cfa2763a4b3e6f9864bc18be6ce8e29ca05f7691c8b659d1658bc4dbc0a6d7cbbc8b415f79772948bac9a5ddcf7a735c75a07c6bab70033c40709fb9ca2def5d4d43b56637b1cb5b70b1f15f048d136821d0b90100500a38a8802025480809044dd70d0086001498ca0b8103142410940942dc3208a709020309a17041810d700f920c404200483080c4f9c089d0e0482302a081b980008084ba02066108aa214b0101a110074b6720848090808400a91c23d1423641208c8e02830501a13050e845000f400b1e1500804934c9052054d033a0704380c48b500d7c2104000024541db103808368a82101f100b611450436846c13584b19014952006360004500e9045a910291f00095484a724400a58c01981b0d21041268a6010044330150e840d680075610c260a611082b6528a83623183462042c9a35078662941c90820011482ca0601849f012e4928010018c1225d020400787068fd114d98807836f9dc5837a30a08379cd93845c7f90a6947070796520e4b883e5bda9e7a59ee4bb99e9b1bca0f8ac3335b4dc95c8f9e3927272908ae25a58e827ce9392747caf336d19661c3688d49e794425d2a8ccf96d3ef86d1f85138eca4800830186a094f69b04ae2c1ba801f6f81d143bf97275b3b940de88127f0e89dca400008025a028f8b68fcd44c7e7f96b90a62a0e0648b89efd7b32d5d7c5734c3ff58da84ffea04517278302823fc575541b965285bc440acfb8d2923222e2a11fefc51134df75f86d82159885104c533c00825208946c24912f3faaefd2c2d937c457f7d5877aa27df7872386f26fc10000801ba0c2ccd7adce5435ef99fdcfc02e71e73dab49a10456b85018ea2b91f0737df7bea034e33f9d7f0219861a62402f1a3261e60767d161a3e4841d1f5edb8da113e261f8aa0285104c533c008301d4c0944571f3a386d1bd18e25d70d117e7067fa0bd9d0880b844a9059cbb000000000000000000000000f5e64589e9429c3097d171f82caacaeef56ccd06000000000000000000000000
```

**Comment by joshua-mir** [comment]
Both of these errors are different issues - the first suggests your disk is full and the second is just a bad block/likely a bad peer, which should just be a warning and not a crash.

**Comment by foxban** [comment]
> Both of these errors are different issues - the first suggests your disk is full and the second is just a bad block/likely a bad peer, which should just be a warning and not a crash.

I think the first one is memory related not disk space, the data disk is 45% free

`/dev/md0        4.0T  2.2T  1.8T  55% /data01`

**Comment by adria0** [comment]
Closing the issue due to its stale state
