### ISSUE TITLE
json_tests/executive.rs: Call of value.unwrap() leads to crash when using DELEGATECALL opcode

### ISSUE THREAD

**Issue by viniul** [openethereum/openethereum#11000]
- **Parity Ethereum version**: Commit 175051bac706a7a5779c014ff0ec4098e6f7b522, master branch
- **Operating system**:Linux
- **Installation**: built from source, with `cargo build --release -p evmbin`

The `ethcore/src/json_tests/executive.rs` file implements the call functions like so:
```
fn call(
		&mut self,
		gas: &U256,
		_sender_address: &Address,
		receive_address: &Address,
		value: Option<U256>,
		data: &[u8],
		_code_address: &Address,
		_call_type: CallType,
		_trap: bool
	) -> Result<MessageCallResult, vm::TrapKind> {
		self.callcreates.push(CallCreate {
			data: data.to_vec(),
			destination: Some(receive_address.clone()),
			gas_limit: *gas,
			value: value.unwrap() // <-- Bug here
		});
		Ok(MessageCallResult::Success(*gas, ReturnData::empty()))
	}
```
The call of `value.unwrap()` is a problem if the code that is tested uses the `DELEGATECALL` opcode, see `ethcore/evm/src/interpreter/mod.rs`, line 568:
```
let value = if instruction == instructions::DELEGATECALL {
     None
}
[...]
ext.call(&call_gas.as_u256(), sender_address, receive_address, value, input, &code_address, call_type, true)
```

As far as I can see, this can lead the `parity-evm` binary to crash when executing state tests that use `DELETECALL`. For instructions on how to reproduce, see below.

What is the expected behavior in this case? I can submit a PR once I know how to best change the `call` function in  `ethcore/src/json_tests/executive.rs` .

--------------------

To reproduce, please do the following:
Go to `ethcore/src/json_tests/executive.rs` and change line 280 from:
```let mut machine = spec::new_frontier_test_machine();```
to ```let mut machine = spec::new_constantinople_test_machine();```.

Create the following state test:
```
{"vincent_test": {
    "_info" : {
        "comment" : "",
        "filledwith" : "testeth 1.5.0.dev2-52+commit.d419e0a2",
        "lllcversion" : "Version: 0.4.26-develop.2018.9.19+commit.785cbf40.Linux.g++",
        "source" : "src/VMTestsFiller/vmTests/suicideFiller.json",
        "sourceHash" : "4622c577440f9db4b3954a1de60bf2fac55886dcb0ec4ecaf906c25bc77372e7"
    },
    "callcreates" : [
    ],
    "env" : {
        "currentCoinbase" : "0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba",
        "currentDifficulty" : "0xb6935a1e0995e",
        "currentGasLimit" : "0x79f39e",
        "currentNumber" : "0x6f1580",
        "currentTimestamp" : "0x5aa6ad63"
    },
    "exec" : {
        "address" : "0x0f572e5295c57f15886f9b263e2f6d2d6c7b5ec6",
        "caller" : "0xcd1722f3947def4cf144679da39c4c32bdc35681",
        "code" : "0x38383838383838373838383938386001f438064b384c23a29b2fb2638c34e668cadac70c250538c7ce37383838393838f438064b3838384b383838c7ce36383838393838f43906bf0d00000000000000081702ad7ec272c710a3aec272c710a3ae8272c710a3aebe223ab01cebf2e64b3838384554383875ce3738383839384bf439064b00",
        "data" : "0x",
        "gas" : "0x493e0",
        "gasPrice" : "0x5af3107a4000",
        "origin" : "0xcd1722f3947def4cf144679da39c4c32bdc35681",
        "value" : "0x0de0b6b3a7640000"
    },
    "gas" : "0x493e0",
    "logs" : "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
    "out" : "0x",
    "post" : {
        "0xcd1722f3947def4cf144679da39c4c32bdc35681" : {
            "balance" : "0x152d02c7e14af6800000",
            "code" : "0x",
            "nonce" : "0x00",
            "storage" : {
            }
        }
    },
    "pre" : {
        "0x0f572e5295c57f15886f9b263e2f6d2d6c7b5ec6" : {
            "balance" : "0",
            "code" : "0x",
            "nonce" : "0x00",
            "storage" : {
            }
        }
    }
}
}
```

Execute the test, which leads to a crash.
```
./target/release/parity-evm stats-jsontests-vm ./ethcore/res/ethereum/tests/VMTests/vmArithmeticTest/vincent_test.json
====================

stack backtrace:
   0:     0x55a09fc5fa1d - backtrace::backtrace::trace::h48d7fc8008400438
   1:     0x55a09fa7224b - panic_hook::gen_panic_msg::h4c6ff2154bb6c944
   2:     0x55a09fa71fce - panic_hook::set_with::{{closure}}::h90455deb4f1a4006
   3:     0x55a09fe4297a - std::panicking::rust_panic_with_hook::hffcefc09751839d1
                        at src/libstd/panicking.rs:481
   4:     0x55a09fe426ee - std::panicking::continue_panic_fmt::hc0f142c930c846fc
                        at src/libstd/panicking.rs:384
   5:     0x55a09fe4fa05 - rust_begin_unwind
                        at src/libstd/panicking.rs:311
   6:     0x55a09fe5a3cb - core::panicking::panic_fmt::h2daf88b2616ca2b2
                        at src/libcore/panicking.rs:85
   7:     0x55a09fe5a87a - core::panicking::panic::h2d0bc53a963fb996
                        at src/libcore/panicking.rs:49
   8:     0x55a09fe73402 - <ethcore::json_tests::executive::TestExt<T,V,B> as vm::ext::Ext>::call::h55f1052d6235a944
   9:     0x55a09fd13e8c - evm::interpreter::Interpreter<Cost>::exec_instruction::hec315bf01ec29c51
  10:     0x55a09fd0ce74 - <evm::interpreter::Interpreter<Cost> as vm::Exec>::exec::hd1c958d2bd39ee61
  11:     0x55a09fe6d2e3 - ethcore::json_tests::executive::do_json_test_for::h3303c27925f56665
  12:     0x55a09fe6874d - <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next::hb1f6ed6f60b17e73
  13:     0x55a09fe77fb4 - ethcore::json_tests::executive::do_json_test::h39229202a8896490
  14:     0x55a09ff01278 - parity_evm::main::h2d720df066a941a1
  15:     0x55a09fe87a92 - std::rt::lang_start::{{closure}}::hd028249991225b27
  16:     0x55a09fefe0ef - main
  17:     0x7f57aed73f32 - __libc_start_main
  18:     0x55a09fa5f50d - _start
  19:                0x0 - <unknown>

Thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new


Aborted (core dumped)
```

**Comment by adria0** [comment]
Closing the issue due to its stale state
