### ISSUE TITLE
DB flush failed; No space left on deviceWhile appending to file But there is space available

### ISSUE THREAD

**Issue by Khurana-Tarun** [openethereum/openethereum#11586]
**OpenEthereum version**: Parity Ethereum 2.7.2
- **Operating system**:  Linux
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

```
stack backtrace:
   0:     0x55f1145d1a0d - <no info>
   1:     0x55f114d8f147 - <no info>
   2:     0x55f1144e4498 - <no info>
   3:     0x55f1158881db - <no info>
   4:     0x55f115887f76 - <no info>
   5:     0x55f114682845 - <no info>
   6:     0x55f114689145 - <no info>
   7:     0x55f1147fda13 - <no info>
   8:     0x55f114a50671 - <no info>
   9:     0x55f114a77bd4 - <no info>
  10:     0x55f114a79b6a - <no info>
  11:     0x55f114a75ad9 - <no info>
  12:     0x55f114a546c5 - <no info>
  13:     0x55f1158a1d2e - <no info>
  14:     0x55f1158a4abf - <no info>
  15:     0x7f9f423dd6b9 - <no info>
  16:     0x7f9f41af141c - <no info>
  17:                0x0 - <no info>

Thread 'IO Worker #1' panicked at 'DB flush failed.: Custom { kind: Other, error: Error { message: "IO error: No space left on deviceWhile appending to file: /data/chains/ethereum/db/906a34e69aec8c0d/archive/db/7791084.log: No space left on device" } }', src/libcore/result.rs:1188
```

```
parity@3ce77f76ebc6:~$ 
parity@3ce77f76ebc6:~$ 
parity@3ce77f76ebc6:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          49G   26G   22G  55% /
tmpfs            64M     0   64M   0% /dev
tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup
/dev/nvme7n1    4.9T  3.9T  757G  84% /data
/dev/nvme11n1    49G   26G   22G  55% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs           7.7G     0  7.7G   0% /proc/acpi
tmpfs           7.7G     0  7.7G   0% /proc/scsi
tmpfs           7.7G     0  7.7G   0% /sys/firmware
parity@3ce77f76ebc6:~$ df -k  /data/chains/ethereum/db/906a34e69aec8c0d/archive/
Filesystem      1K-blocks       Used Available Use% Mounted on
/dev/nvme7n1   5160481296 4147681168 793685564  84% /data
parity@3ce77f76ebc6:~$ 


```

**Comment by Khurana-Tarun** [comment]
```
====================

stack backtrace:
   0:     0x55f1145d1a0d - <no info>
   1:     0x55f114d8f147 - <no info>
   2:     0x55f1144e4498 - <no info>
   3:     0x55f1158881db - <no info>
   4:     0x55f115887f76 - <no info>
   5:     0x55f114682845 - <no info>
   6:     0x55f114689145 - <no info>
   7:     0x55f1147fda13 - <no info>
   8:     0x55f114a50671 - <no info>
   9:     0x55f114a77bd4 - <no info>
  10:     0x55f114a79b6a - <no info>
  11:     0x55f114a75ad9 - <no info>
  12:     0x55f114a546c5 - <no info>
  13:     0x55f1158a1d2e - <no info>
  14:     0x55f1158a4abf - <no info>
  15:     0x7f9f423dd6b9 - <no info>
  16:     0x7f9f41af141c - <no info>
  17:                0x0 - <no info>

Thread 'IO Worker #1' panicked at 'DB flush failed.: Custom { kind: Other, error: Error { message: "IO error: No space left on deviceWhile appending to file: /data/chains/ethereum/db/906a34e69aec8c0d/archive/db/7791084.log: No space left on device" } }', src/libcore/result.rs:1188

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new


2020-03-26 04:12:37 UTC Finishing work, please wait...
2020-03-26 04:25:37 UTC Starting Parity-Ethereum/v2.7.2-stable-2662d19-20200206/x86_64-unknown-linux-gnu/rustc1.41.0
2020-03-26 04:25:37 UTC Keys path /data/keys/ethereum
2020-03-26 04:25:37 UTC DB path /data/chains/ethereum/db/906a34e69aec8c0d
2020-03-26 04:25:37 UTC State DB configuration: archive +Trace
2020-03-26 04:25:37 UTC Operating mode: active
2020-03-26 04:25:37 UTC Warning: Warp Sync is disabled because tracing is turned on.
2020-03-26 04:25:38 UTC DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col8, col7, col6, col5, col4, col0, col1, col2, col3, attempting repair
2020-03-26 04:29:39 UTC Starting Parity-Ethereum/v2.7.2-stable-2662d19-20200206/x86_64-unknown-linux-gnu/rustc1.41.0
2020-03-26 04:29:39 UTC Keys path /data/keys/ethereum
2020-03-26 04:29:39 UTC DB path /data/chains/ethereum/db/906a34e69aec8c0d
2020-03-26 04:29:39 UTC State DB configuration: archive +Trace
2020-03-26 04:29:39 UTC Operating mode: active
2020-03-26 04:29:39 UTC Warning: Warp Sync is disabled because tracing is turned on.
2020-03-26 04:29:40 UTC DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col4, col2, col3, col0, attempting repair
2020-03-27 00:22:59 UTC Starting Parity-Ethereum/v2.7.2-stable-2662d19-20200206/x86_64-unknown-linux-gnu/rustc1.41.0
2020-03-27 00:22:59 UTC Keys path /data/keys/ethereum
2020-03-27 00:22:59 UTC DB path /data/chains/ethereum/db/906a34e69aec8c0d
2020-03-27 00:22:59 UTC State DB configuration: archive +Trace
2020-03-27 00:22:59 UTC Operating mode: active
2020-03-27 00:22:59 UTC Warning: Warp Sync is disabled because tracing is turned on.
2020-03-27 00:22:59 UTC DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col4, col2, col3, col0, attempting repair
2020-03-27 01:07:25 UTC Starting Parity-Ethereum/v2.7.2-stable-2662d19-20200206/x86_64-unknown-linux-gnu/rustc1.41.0
2020-03-27 01:07:25 UTC Keys path /data/keys/ethereum
2020-03-27 01:07:25 UTC DB path /data/chains/ethereum/db/906a34e69aec8c0d
2020-03-27 01:07:25 UTC State DB configuration: archive +Trace
2020-03-27 01:07:25 UTC Operating mode: active
2020-03-27 01:07:25 UTC Warning: Warp Sync is disabled because tracing is turned on.
2020-03-27 01:07:25 UTC DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col1, col0, col3, col2, col4, attempting repair
2020-03-27 01:18:48 UTC Starting Parity-Ethereum/v2.7.2-stable-2662d19-20200206/x86_64-unknown-linux-gnu/rustc1.41.0
2020-03-27 01:18:48 UTC Keys path /data/keys/ethereum
2020-03-27 01:18:48 UTC DB path /data/chains/ethereum/db/906a34e69aec8c0d
2020-03-27 01:18:48 UTC State DB configuration: archive +Trace
2020-03-27 01:18:48 UTC Operating mode: active
2020-03-27 01:18:48 UTC Warning: Warp Sync is disabled because tracing is turned on.
2020-03-27 01:18:48 UTC DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col4, col2, col3, col0, attempting repair
2020-03-27 01:23:55 UTC Starting Parity-Ethereum/v2.7.2-stable-2662d19-20200206/x86_64-unknown-linux-gnu/rustc1.41.0
2020-03-27 01:23:55 UTC Keys path /data/keys/ethereum
2020-03-27 01:23:55 UTC DB path /data/chains/ethereum/db/906a34e69aec8c0d
2020-03-27 01:23:55 UTC State DB configuration: archive +Trace
2020-03-27 01:23:55 UTC Operating mode: active
2020-03-27 01:23:55 UTC Warning: Warp Sync is disabled because tracing is turned on.
2020-03-27 01:23:56 UTC DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col4, col2, col3, col0, attempting repair
2020-03-27 02:25:41 UTC Starting Parity-Ethereum/v2.7.2-stable-2662d19-20200206/x86_64-unknown-linux-gnu/rustc1.41.0
2020-03-27 02:25:41 UTC Keys path /data/keys/ethereum
2020-03-27 02:25:41 UTC DB path /data/chains/ethereum/db/906a34e69aec8c0d
2020-03-27 02:25:41 UTC State DB configuration: archive +Trace
2020-03-27 02:25:41 UTC Operating mode: active
2020-03-27 02:25:41 UTC Warning: Warp Sync is disabled because tracing is turned on.
2020-03-27 02:25:41 UTC DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col1, col0, col3, col2, col4, attempting repair
2020-03-27 02:42:43 UTC Starting Parity-Ethereum/v2.7.2-stable-2662d19-20200206/x86_64-unknown-linux-gnu/rustc1.41.0
2020-03-27 02:42:43 UTC Keys path /data/keys/ethereum
2020-03-27 02:42:43 UTC DB path /data/chains/ethereum/db/906a34e69aec8c0d
2020-03-27 02:42:43 UTC State DB configuration: archive +Trace
2020-03-27 02:42:43 UTC Operating mode: active
2020-03-27 02:42:43 UTC Warning: Warp Sync is disabled because tracing is turned on.
2020-03-27 02:42:44 UTC DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col1, col0, col3, col2, col4, attempting repair
2020-03-27 07:31:34 UTC Starting Parity-Ethereum/v2.7.2-stable-2662d19-20200206/x86_64-unknown-linux-gnu/rustc1.41.0
2020-03-27 07:31:34 UTC Keys path /data/keys/ethereum
2020-03-27 07:31:34 UTC DB path /data/chains/ethereum/db/906a34e69aec8c0d
2020-03-27 07:31:34 UTC State DB configuration: archive +Trace
2020-03-27 07:31:34 UTC Operating mode: active
2020-03-27 07:31:34 UTC Warning: Warp Sync is disabled because tracing is turned on.
2020-03-27 07:31:34 UTC DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col1, col0, col3, col2, col4, attempting repair


```

**Comment by niklasad1** [comment]
Hey, 

Can you run `fsck` on your disk just to make sure it's nothing wrong with it?

**Comment by Khurana-Tarun** [comment]
There is no issue with the disk

```
ubuntu@ip-xx:~$ sudo fsck /dev/xvdi
fsck from util-linux 2.31.1
e2fsck 1.44.1 (24-Mar-2018)
/dev/xvdi: clean, 77472/327680000 files, 1057521055/1310720000 blocks
ubuntu@ip-xx~$ echo $?
0


```

**Comment by niklasad1** [comment]
//cc @ordian anything you have seen in rocksdb?

Seems like we have a similar issue in https://github.com/paritytech/substrate/issues/4270

**Comment by ordian** [comment]
I haven't seen this issue myself, hard to say what could the issue here. Could be an issue with RocksDB, e.g. https://github.com/facebook/rocksdb/issues/6316 (which is fixed on master). Somehow the db ended up in a corrupted state, I'm not sure if it's possible to recover it :/

**Comment by c0deright** [comment]
You might wanna read that error message again:

IO error: No space left on device While appending to file: /data/chains/ethereum/db/906a34e69aec8c0d/archive/db/7791084.log: No space left on device

Your disk was/is full. No surprise you're running into problems.

**Comment by Khurana-Tarun** [comment]
There was around 3gb space in the volume at the time of this error.
 @c0deright
