### ISSUE TITLE
Kotti network: panics on archive node

### ISSUE THREAD

**Issue by YazzyYaz** [openethereum/openethereum#11593]
**OpenEthereum version**: 2.8.0
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: kotti
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

With the latest Parity Nightly compile that includes [these](https://github.com/openethereum/openethereum/pull/11584/files) changes to test out Kotti network again resulted in a panic error as shown in the following logs:
```
2020-03-31 12:30:12 UTC Starting Open-Ethereum/v2.8.0-nightly-70c4ed7fa-20200317/x86_64-unknown-linux-gnu/rustc1.42.0
2020-03-31 12:30:12 UTC Keys path /home/yaz/.local/share/io.parity.ethereum/keys/kotti    
2020-03-31 12:30:12 UTC DB path /home/yaz/.local/share/io.parity.ethereum/chains/kotti/db/717b12a127188bca
2020-03-31 12:30:12 UTC State DB configuration: archive +Fat +Trace
2020-03-31 12:30:12 UTC Operating mode: active              
2020-03-31 12:30:12 UTC Configured for Kotti Testnet using Clique engine
2020-03-31 12:30:19 UTC Public node URL: enode://44d72b3be8fd36db271dfb9ce022debe02508b5ee1fe93f5069a081ab65bffbd9b55a4cd529c89d1ee89dba9eaeb014ffd7d1f655dc18f55930
f6cf62bd66862@10.128.15.240:30000                     
2020-03-31 12:30:20 UTC Panic occurred, see stderr for details
                                                                                                                                                         
====================
                                   
stack backtrace:
   0: panic_hook::gen_panic_msg                             
   1: panic_hook::set_with::{{closure}}
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476                                                                                                                         
   3: rust_begin_unwind                                                                                                                                             
             at src/libstd/panicking.rs:380
   4: core::panicking::panic_fmt                                                                                                                           
             [40/1815]
             at src/libcore/panicking.rs:85
   5: core::option::expect_failed
             at src/libcore/option.rs:1191
   6: <trace::db::TraceDB<T> as trace::Database>::import
   7: ethcore::client::client::Importer::import_verified_blocks
   8: <ethcore_service::service::ClientIoHandler<C> as ethcore_io::IoHandler<common_types::io_message::ClientIoMessage<C>>>::message
   9: ethcore_io::service_mio::IoChannel<Message>::send_sync
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  13: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:80
  14: start_thread
  15: __clone
Thread 'Verifier #0' panicked at 'Traces database is incomplete.', /home/yaz/openethereum/ethcore/trace/src/db.rs:248
This is a bug. Please report it at:
    https://github.com/OpenEthereum/open-ethereum/issues/new
2020-03-31 12:30:20 UTC Finishing work, please wait...
2020-03-31 12:30:21 UTC Panic occurred, see stderr for details
====================
stack backtrace:
   0: panic_hook::gen_panic_msg
   1: panic_hook::set_with::{{closure}}
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
   3: rust_begin_unwind
             at src/libstd/panicking.rs:380
   4: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
```

I'm running in Archive mode using the following command:
```
parity --chain=kotti --port 30000 --ws-interface all --ws-apis="web3","eth","net","parity","pubsub","traces" --ws-origins all --ws-hosts all --jsonrpc-apis="web3","eth","net","parity","pubsub","traces" --tracing=on --fat-db=on --pruning=archive --jsonrpc-cors all --jsonrpc-hosts all --jsonrpc-interface all --mode active --reserved-peers=reserved-peers.txt
```

Not sure what's happening.

## Actual

As shown in error logs above, it results in a panic.

## Expected

It's expected to start syncing instead.

**Comment by q9f** [comment]
Notably, I recommended @YazzyYaz to reset the database but he ignored me and just downgraded Parity to 2.7.2 and apparently it works. So the panic is an actual bug of an archive/tracing node database unreadable by 2.8.0 nightly. :point_up:

**Comment by YazzyYaz** [comment]
I couldn't reset the database since I had deleted it. 

To further add, I also ran Mordor on the latest 2.8.0 nightly and it worked with the latest changes by @q9f.  So it must be Kotti only that's experiencing the unreadable node database by the latest nightly.

**Comment by q9f** [comment]
Then it's just a corrupted database. delete and reset is the same.

**Comment by YazzyYaz** [comment]
Ah ok, thanks. To clarify steps taken, what I did was delete the database and reran it and it didn't work there with latest nightly. This is the documented issue here.

It did work in 2.7.2 stable which is what I'm currently syncing now as an alternative.

**Comment by ordian** [comment]
To clarify,
`./parity-v2.7.2 --chain kotti.json --tracing=on --fat-db=on --pruning=archive` works, while
`./parity-v2.8.0 --chain kotti.json --tracing=on --fat-db=on --pruning=archive` panics
where kotti.json is [from master](https://raw.githubusercontent.com/openethereum/openethereum/master/ethcore/res/ethereum/kotti.json).

So this is a regression on master.

**Comment by niklasad1** [comment]
Does it panic on the commit before i.e.,  https://github.com/openethereum/openethereum/commit/302a388d964558a4649f92636ed3665943b77d17?

**Comment by niklasad1** [comment]
@YazzyYaz can you try this on [latest master](https://github.com/openethereum/openethereum/commit/4b5e9ddfa66e0e5082281034b148546278c2a315)? I could not reproduce this at least.

**Comment by dvdplm** [comment]
I believe this is fixed. @YazzyYaz let us know if you disagree.
