### ISSUE TITLE
Error: Failed to check for transaction receipt

### ISSUE THREAD

**Issue by noahsalvadordenjo** [openethereum/openethereum#11738]
```
web3.eth.personal.unlockAccount('0x12AdF37d82D978fD72bfcC95Ca09C0D91Bb4F4d3', password).then(unlock => {
    if(unlock) {
        web3.eth.sendTransaction({
            value: 18595137371577333,
            from: '0x12AdF37d82D978fD72bfcC95Ca09C0D91Bb4F4d3',
            to: '0x478a286CD2Cc5D997c2AA45C6CA79A2b7c1676eD'
        }).then(console.log)
    }
})
```
What am i doing wrong am i missing something in the startline?

**Comment by adria0** [comment]
@noahsalvadordenjo what is the current result?

**Comment by noahsalvadordenjo** [comment]
```
(node:16496) UnhandledPromiseRejectionWarning: Error: Failed to check for transaction receipt:
{}
    at Object._fireError (C:\Users\noahv\documents\cryschyp\backend\nodejs\node_modules\web3-utils\src\index.js:57:17)
    at C:\Users\noahv\documents\cryschyp\backend\nodejs\node_modules\web3-core-method\src\index.js:272:27
(node:16496) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 20)
(node:16496) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the 
Node.js process with a non-zero exit code.
```

**Comment by adria0** [comment]
It seems that this error is more related to javascript/web3.js than to the underlying connection to OpenEthereum RPC. Web3Js github is in https://github.com/ethereum/web3.js/

**Comment by noahsalvadordenjo** [comment]
Alright I will post an issue there as well, but with ganache it works fine

**Comment by noahsalvadordenjo** [comment]
I ran this in the console
```
./openethereum --jsonrpc-interface "10.128.0.4" --jsonrpc-apis "all" --js
onrpc-hosts "all" --jsonrpc-cors "all"
```
