### ISSUE TITLE
Thread 'IO Worker #1' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', ethcore/src/client/traits.rs:93

### ISSUE THREAD

**Issue by samsends** [openethereum/openethereum#129]
_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: 3.1.0

- **Operating system**: Linux (ContainerOS)
- **Installation**: Docker
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes?

```

2020-11-25 18:53:29 UTC Panic occured, see stderr for details


====================

stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>


Thread 'IO Worker #1' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', ethcore/src/client/traits.rs:93

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2020-11-25 18:53:29 UTC Finishing work, please wait...
Error: 1

```

right before there is a big print out of pending tx's?

```

0x106203f78b4d8e2e409d691aeda9ed04ac0ae1bb), value: 900000000000000000, data: [] }, v: 38, r: 88260242718506969700986126168570193435822748894697201763670847409210729653004, s: 33708481202280534376041378628966428020375159339692232358965324599540581868977, hash: 0x0fb87a0e4ac836f36749fbb4a3b4acc4d054f4be522ce5c4af929da164bad690 }
[Tx 202] UnverifiedTransaction { unsigned: Transaction { nonce: 7, gas_price: 56000000000, gas: 48335, action: Call(0x40e45890dff79e7d533797d964e64a2c0121f49a), value: 0, data: [169, 5, 156, 187, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 221, 42, 49, 208, 75, 89, 217, 20, 184, 44, 49, 86, 87, 5, 30, 28, 80, 205, 199, 111, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 53, 164, 233, 0] }, v: 38, r: 70477206207926262496174118802002622839888229484074582331573811398623584087231, s: 13423473625145708366924100550055024931824395991372400202523352431805190078312, hash: 0xe2d01c9c860b8614b730b3c1ce8cfc00e580195e25ea80e552259009b8fcbcc9 }

```

**Comment by 8YOne** [comment]
I am having the same issue.

Running on Ubuntu 20.04.1 with OpenEthereum v3.1.0


```Nov 26 21:45:12 artanis openethereum[46529]: [Tx 194] UnverifiedTransaction { unsigned: Transaction { nonce: 122378, gas_price: 77000000000, gas: 400000, action: Create, value: 0, data: [96, 128, 96, 64, 82, 52, 128, 21, 97, 0, 16, 87, 96, 0, 128, 25  3, 91, 80, 96, 64, 81, 96, 32, 128, 97, 4, 20, 131, 57, 129, 1, 96, 64, 82, 81, 96, 0, 128, 84, 96, 1, 96, 160, 96, 2, 10, 3, 144, 146, 22, 96, 1, 96, 160, 96, 2, 10, 3, 25, 146, 131, 22, 51, 23, 144, 146, 22, 145, 144, 145, 23, 144, 85, 97, 3, 189,   128, 97, 0, 87, 96, 0, 57, 96, 0, 243, 0, 96, 128, 96, 64, 82, 96, 4, 54, 16, 97, 0, 97, 87, 99, 255, 255, 255, 255, 124, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 96, 0, 53, 4, 22, 99, 133, 104, 82, 58, 1  29, 20, 97, 0, 216, 87, 128, 99, 141, 165, 203, 91, 20, 97, 0, 252, 87, 128, 99, 183, 110, 169, 98, 20, 97, 1, 45, 87, 128, 99, 242, 253, 227, 139, 20, 97, 1, 135, 87, 91, 96, 0, 128, 84, 96, 64, 81, 96, 1, 96, 160, 96, 2, 10, 3, 144, 145, 22, 145, 5  2, 145, 144, 129, 129, 129, 133, 135, 90, 241, 146, 80, 80, 80, 21, 97, 0, 209, 87, 96, 0, 84, 96, 64, 128, 81, 52, 129, 82, 144, 81, 96, 1, 96, 160, 96, 2, 10, 3, 144, 146, 22, 145, 51, 145, 127, 85, 72, 200, 55, 171, 6, 140, 245, 106, 44, 36, 121,   223, 8, 130, 164, 146, 47, 210, 3, 237, 183, 81, 115, 33, 131, 29, 149, 7, 140, 95, 98, 145, 144, 129, 144, 3, 96, 32, 1, 144, 163, 97, 0, 214, 86, 91, 96, 0, 128, 253, 91, 0, 91, 52, 128, 21, 97, 0, 228, 87, 96, 0, 128, 253, 91, 80, 97, 0, 214, 96,   1, 96, 160, 96, 2, 10, 3, 96, 4, 53, 22, 96, 36, 53, 97, 1, 168, 86, 91, 52, 128, 21, 97, 1, 8, 87, 96, 0, 128, 253, 91, 80, 97, 1, 17, 97, 2, 68, 86, 91, 96, 64, 128, 81, 96, 1, 96, 160, 96, 2, 10, 3, 144, 146, 22, 130, 82, 81, 144, 129, 144, 3, 96,   32, 1, 144, 243, 91, 96, 64, 128, 81, 96, 32, 96, 4, 96, 36, 128, 53, 130, 129, 1, 53, 96, 31, 129, 1, 133, 144, 4, 133, 2, 134, 1, 133, 1, 144, 150, 82, 133, 133, 82, 97, 0, 214, 149, 131, 53, 96, 1, 96, 160, 96, 2, 10, 3, 22, 149, 54, 149, 96, 68,   148, 145, 147, 144, 145, 1, 145, 144, 129, 144, 132, 1, 131, 130, 128, 130, 132, 55, 80, 148, 151, 80, 97, 2, 83, 150, 80, 80, 80, 80, 80, 80, 80, 86, 91, 52, 128, 21, 97, 1, 147, 87, 96, 0, 128, 253, 91, 80, 97, 0, 214, 96, 1, 96, 160, 96, 2, 10, 3  , 96, 4, 53, 22, 97, 2, 241, 86, 91, 96, 0, 84, 96, 1, 96, 160, 96, 2, 10, 3, 22, 51, 20, 97, 1, 191, 87, 96, 0, 128, 253, 91, 96, 0, 128, 84, 96, 64, 128, 81, 127, 169, 5, 156, 187, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0  , 0, 0, 0, 0, 0, 129, 82, 96, 1, 96, 160, 96, 2, 10, 3, 146, 131, 22, 96, 4, 130, 1, 82, 96, 36, 129, 1, 133, 144, 82, 144, 81, 145, 133, 22, 146, 99, 169, 5, 156, 187, 146, 96, 68, 128, 132, 1, 147, 130, 144, 3, 1, 129, 131, 135, 128, 59, 21, 128, 2  1, 97, 2, 40, 87, 96, 0, 128, 253, 91, 80, 90, 241, 21, 128, 21, 97, 2, 60, 87, 61, 96, 0, 128, 62, 61, 96, 0, 253, 91, 80, 80, 80, 80, 80, 80, 86, 91, 96, 0, 84, 96, 1, 96, 160, 96, 2, 10, 3, 22, 129, 86, 91, 96, 0, 84, 96, 1, 96, 160, 96, 2, 10, 3,   22, 51, 20, 97, 2, 106, 87, 96, 0, 128, 253, 91, 129, 96, 1, 96, 160, 96, 2, 10, 3, 22, 52, 130, 96, 64, 81, 128, 130, 128, 81, 144, 96, 32, 1, 144, 128, 131, 131, 96, 0, 91, 131, 129, 16, 21, 97, 2, 160, 87, 129, 129, 1, 81, 131, 130, 1, 82, 96, 32  , 1, 97, 2, 136, 86, 91, 80, 80, 80, 80, 144, 80, 144, 129, 1, 144, 96, 31, 22, 128, 21, 97, 2, 205, 87, 128, 130, 3, 128, 81, 96, 1, 131, 96, 32, 3, 97, 1, 0, 10, 3, 25, 22, 129, 82, 96, 32, 1, 145, 80, 91, 80, 145, 80, 80, 96, 0, 96, 64, 81, 128, 1  31, 3, 129, 133, 135, 90, 241, 146, 80, 80, 80, 21, 21, 97, 2, 237, 87, 96, 0, 128, 253, 91, 80, 80, 86, 91, 96, 0, 84, 96, 1, 96, 160, 96, 2, 10, 3, 22, 51, 20, 97, 3, 8, 87, 96, 0, 128, 253, 91, 97, 3, 17, 129, 97, 3, 20, 86, 91, 80, 86, 91, 96, 1,   96, 160, 96, 2, 10, 3, 129, 22, 21, 21, 97, 3, 41, 87, 96, 0, 128, 253, 91, 96, 0, 128, 84, 96, 64, 81, 96, 1, 96, 160, 96, 2, 10, 3, 128, 133, 22, 147, 146, 22, 145, 127, 139, 224, 7, 156, 83, 22, 89, 20, 19, 68, 205, 31, 208, 164, 242, 132, 25, 73  , 127, 151, 34, 163, 218, 175, 227, 180, 24, 111, 107, 100, 87, 224, 145, 163, 96, 0, 128, 84, 115, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 25, 22, 96, 1, 96, 160, 96, 2, 10, 3, 146, 144, 14  6, 22, 145, 144, 145, 23, 144, 85, 86, 0, 161, 101, 98, 122, 122, 114, 48, 88, 32, 141, 40, 197, 179, 167, 60, 47, 78, 87, 97, 97, 213, 209, 141, 210, 231, 237, 231, 229, 228, 210, 101, 83, 85, 60, 68, 112, 67, 100, 126, 178, 136, 0, 41, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 169, 16, 249, 42, 205, 175, 72, 143, 166, 239, 2, 23, 79, 184, 98, 8, 173, 119, 34, 186] }, v: 27, r: 102814332707649066052675715508996366189825154723914357171078177789984907986799, s: 16972804029765974108177872981386509331709  737457064250482473049174199250011904, hash: 0x7e76fb0370facadc01a659bfa3ad8118b7cf79201d3087d6dfce92086d19bddb }
Nov 26 21:45:12 artanis openethereum[46529]: [Tx 195] UnverifiedTransaction { unsigned: Transaction { nonce: 338, gas_price: 77000000000, gas: 219861, action: Call(0x8400d94a5cb0fa0d041a3788e395285d61c9ee5e), value: 0, data: [169, 5, 156, 187, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 58, 124, 36, 198, 94, 166, 95, 195, 207, 24, 187, 116, 108, 81, 163, 218, 205, 142, 179, 111, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, 72, 118, 232, 0] }, v: 38, r: 11604899405  322114964297067432112092110261135396938575930556094615459964722819, s: 5051342865605780639451581042557787789035856045309253483255920818889623574844, hash: 0xf333c65f58ce8097a1e2eba0e971c8a34a2b67dc32fbad83037a989c36e3a30c }
Nov 26 21:45:12 artanis openethereum[46529]: [Tx 196] UnverifiedTransaction { unsigned: Transaction { nonce: 87, gas_price: 77000000000, gas: 83601, action: Call(0x69e8b9528cabda89fe846c67675b5d73d463a916), value: 0, data: [169, 5, 156, 187, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 244, 87, 22, 121, 52, 195, 92, 55, 59, 158, 173, 153, 9, 202, 55, 215, 28, 133, 40, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 63, 192, 71, 73, 72, 243, 96, 0, 0] }, v: 38, r: 3248945847804665  4790170855343817639422064243796313465822673060045217225029960, s: 3975424506569953102420764936102112309193004555782057560728593712575448433092, hash: 0x12a8d50f88566f54364d2e066e1b9507d3fae2e4f6582c0dd91e69f32136c6c8 }
Nov 26 21:45:12 artanis openethereum[46529]: [Tx 197] UnverifiedTransaction { unsigned: Transaction { nonce: 88, gas_price: 77000001357, gas: 83619, action: Call(0x69e8b9528cabda89fe846c67675b5d73d463a916), value: 0, data: [169, 5, 156, 187, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 147, 100, 112, 233, 209, 136, 224, 57, 23, 20, 91, 137, 241, 44, 56, 74, 161, 31, 247, 243, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 62, 221, 37, 219, 212, 15, 168, 0, 0] }, v: 38, r: 1117524252  12563584941501476564701074502000894161618160900329862177571575179860, s: 22485201673643086597283933971552382617717080359824574360544182867810923722102, hash: 0x9c09a6534d093f9dce0e347b4cef7190895eea6f3c6d50bcf2281eee85bd4166 }
Nov 26 21:45:12 artanis openethereum[46529]: [Tx 198] UnverifiedTransaction { unsigned: Transaction { nonce: 46602, gas_price: 77000000000, gas: 21000, action: Call(0x4422e1940926009d46b350fac5f0cd5a96f0c69c), value: 10534485000000000, data: [] }, v:   38, r: 100973739014227601064475361387633666254944878558116870217874106331205171086577, s: 57590823531009180680293637777604149856407325464474853447748686131967081223715, hash: 0x5b6da56a5f677f22ccf3bdced53345b27383776a633f04be9d528e0b7a3086b1 }
Nov 26 21:45:12 artanis openethereum[46529]: [Tx 199] UnverifiedTransaction { unsigned: Transaction { nonce: 857, gas_price: 77000000000, gas: 21000, action: Call(0xd2666eff52c2383eae7ce87361563fc3fcb499dc), value: 0, data: [] }, v: 27, r: 8641704756  4963484638998536551575559583386445463392451957679900009226929582831, s: 43573654107595202798214750308852568939002034600508437043437803846095776013655, hash: 0xa3de26e6a7c04602ff12a55dbaadb5df9a59d4678fea02b6bcaf0e61f0d7e680 }
Nov 26 21:45:26 artanis openethereum[46529]: 2020-11-26 21:45:26 UTC Syncing #11335001 0x3058…8a0f     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11335103   11/25 peers    112 KiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
Nov 26 21:45:31 artanis openethereum[46529]: 2020-11-26 21:45:31 UTC Syncing #11335001 0x3058…8a0f     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11335103   11/25 peers    112 KiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
Nov 26 21:46:01 artanis openethereum[46529]: 2020-11-26 21:46:01 UTC   22/25 peers    112 KiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
Nov 26 21:46:21 artanis openethereum[46529]: 2020-11-26 21:46:21 UTC Syncing #11335001 0x3058…8a0f     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11335103   23/25 peers    112 KiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
Nov 26 21:46:26 artanis openethereum[46529]: 2020-11-26 21:46:26 UTC Syncing #11335001 0x3058…8a0f     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11335103   25/25 peers    112 KiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
Nov 26 21:46:31 artanis openethereum[46529]: 2020-11-26 21:46:31 UTC Syncing #11335001 0x3058…8a0f     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11335103   25/25 peers    112 KiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
Nov 26 21:46:47 artanis openethereum[46529]: 2020-11-26 21:46:47 UTC Panic occured, see stderr for details
Nov 26 21:46:47 artanis openethereum[46529]: ====================
Nov 26 21:46:47 artanis openethereum[46529]: stack backtrace:
Nov 26 21:46:47 artanis openethereum[46529]:    0: <unknown>
Nov 26 21:46:47 artanis openethereum[46529]:    1: <unknown>
Nov 26 21:46:47 artanis openethereum[46529]:    2: <unknown>
Nov 26 21:46:47 artanis openethereum[46529]:    3: <unknown>
Nov 26 21:46:47 artanis openethereum[46529]:    4: <unknown>
Nov 26 21:46:47 artanis openethereum[46529]:    5: <unknown>
Nov 26 21:46:47 artanis openethereum[46529]:    6: <unknown>
Nov 26 21:46:47 artanis openethereum[46529]:    7: <unknown>
Nov 26 21:46:47 artanis openethereum[46529]:    8: <unknown>
Nov 26 21:46:47 artanis openethereum[46529]:    9: <unknown>
Nov 26 21:46:47 artanis openethereum[46529]:   10: <unknown>
Nov 26 21:46:47 artanis openethereum[46529]:   11: <unknown>
Nov 26 21:46:47 artanis openethereum[46529]:   12: <unknown>
Nov 26 21:46:47 artanis openethereum[46529]:   13: <unknown>
Nov 26 21:46:47 artanis openethereum[46529]:   14: <unknown>
Nov 26 21:46:47 artanis openethereum[46529]:   15: <unknown>
Nov 26 21:46:47 artanis openethereum[46529]:   16: <unknown>
Nov 26 21:46:47 artanis openethereum[46529]:   17: <unknown>
Nov 26 21:46:47 artanis openethereum[46529]:   18: start_thread
Nov 26 21:46:47 artanis openethereum[46529]:   19: __clone
Nov 26 21:46:47 artanis openethereum[46529]: Thread 'IO Worker #1' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', ethcore/src/client/traits.rs:93
Nov 26 21:46:47 artanis openethereum[46529]: This is a bug. Please report it at:
Nov 26 21:46:47 artanis openethereum[46529]:     https://github.com/openethereum/openethereum/issues/new
Nov 26 21:46:47 artanis openethereum[46529]: 2020-11-26 21:46:47 UTC Finishing work, please wait...
Nov 26 21:46:48 artanis openethereum[46529]: Error: 1
Nov 26 21:46:49 artanis openethereum[46602]: 2020-11-26 21:46:49 UTC Starting OpenEthereum/v3.1.0-stable-2072341-20201102/x86_64-linux-gnu/rustc1.47.0
Nov 26 21:46:49 artanis openethereum[46602]: 2020-11-26 21:46:49 UTC Keys path /home/ethnode/.local/share/openethereum/keys/ethereum
Nov 26 21:46:49 artanis openethereum[46602]: 2020-11-26 21:46:49 UTC DB path /home/ethnode/.local/share/openethereum/chains/ethereum/db/906a34e69aec8c0d
Nov 26 21:46:49 artanis openethereum[46602]: 2020-11-26 21:46:49 UTC State DB configuration: fast
Nov 26 21:46:49 artanis openethereum[46602]: 2020-11-26 21:46:49 UTC Operating mode: active
Nov 26 21:46:49 artanis openethereum[46602]: 2020-11-26 21:46:49 UTC Configured for Ethereum using Ethash engine
Nov 26 21:46:49 artanis openethereum[46602]: 2020-11-26 21:46:49 UTC Listening for new connections on 127.0.0.1:8546.
```

**Comment by samsends** [comment]
yo @8YOne what was your config?

**Comment by 8YOne** [comment]
> yo @8YOne what was your config?

@samsends Default configs

**Comment by roninkaizen** [comment]
does the docker build include rust-
if so could you check, if it was builded with rust 1.4.8
which actually does not work!

**Comment by WMEth** [comment]
Seeing the same bug, version OpenEthereum/v3.1.0-stable-2072341-20201102/x86_64-linux-gnu/rustc1.47.0

Running with ./openethereum -d /mnt/volume_openethereum_200/openethereum --cache-size 2048

**Comment by AdvancedStyle** [comment]
I have the same problem running v3.1.0 with all default config.  
```
Nov 28 09:22:51 vmi480454.contaboserver.net openethereum[104954]: 2020-11-28 09:22:51  Syncing #11343540 0xa35a…8e8f     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11343739   28/50 peers   728 bytes chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
Nov 28 09:22:56 vmi480454.contaboserver.net openethereum[104954]: 2020-11-28 09:22:56  Syncing #11343540 0xa35a…8e8f     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11343739   28/50 peers   728 bytes chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]: 2020-11-28 09:23:00  Panic occured, see stderr for details
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]: ====================
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]: stack backtrace:
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    0: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    1: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    2: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    3: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    4: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    5: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    6: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    7: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    8: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    9: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   10: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   11: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   12: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   13: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   14: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   15: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   16: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   17: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   18: start_thread
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   19: __clone
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]: Thread 'IO Worker #0' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', ethcore/src/client/traits.rs:93
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]: This is a bug. Please report it at:
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:     https://github.com/openethereum/openethereum/issues/new
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]: 2020-11-28 09:23:00  Finishing work, please wait...
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]: 2020-11-28 09:23:00  Panic occured, see stderr for details
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]: ====================
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]: stack backtrace:
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    0: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    1: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    2: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    3: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    4: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    5: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    6: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    7: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    8: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    9: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   10: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   11: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   12: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   13: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   14: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   15: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   16: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   17: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   18: start_thread
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   19: __clone
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]: Thread 'IO Worker #1' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', ethcore/src/client/traits.rs:93
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]: This is a bug. Please report it at:
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:     https://github.com/openethereum/openethereum/issues/new
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]: 2020-11-28 09:23:00  Panic occured, see stderr for details
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]: ====================
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]: stack backtrace:
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    0: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    1: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    2: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    3: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    4: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    5: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    6: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    7: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    8: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:    9: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   10: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   11: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   12: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   13: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   14: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   15: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   16: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   17: <unknown>
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   18: start_thread
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:   19: __clone
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]: Thread 'IO Worker #2' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', ethcore/src/client/traits.rs:93
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]: This is a bug. Please report it at:
Nov 28 09:23:00 vmi480454.contaboserver.net openethereum[104954]:     https://github.com/openethereum/openethereum/issues/new
Nov 28 09:23:01 vmi480454.contaboserver.net openethereum[104954]: Error: 1
Nov 28 09:23:01 vmi480454.contaboserver.net systemd[1]: openethereum.service: Main process exited, code=exited, status=1/FAILURE
Nov 28 09:23:01 vmi480454.contaboserver.net systemd[1]: openethereum.service: Failed with result 'exit-code'.
Nov 28 09:23:01 vmi480454.contaboserver.net systemd[1]: openethereum.service: Scheduled restart job, restart counter is at 1651.

```

**Comment by leovigna** [comment]
I also have this issue.

**Comment by leovigna** [comment]
I rebbuilt openthereum with rust 1.46 and got a stack backtrace:
```
====================

stack backtrace:
   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:530
   2: rust_begin_unwind
             at src/libstd/panicking.rs:437
   3: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   4: core::option::expect_failed
             at src/libcore/option.rs:1261
   5: ethcore::client::traits::Nonce::latest_nonce
   6: <ethcore::miner::pool_client::CachedNonceClient<C> as ethcore_miner::pool::client::NonceClient>::account_nonce
   7: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   8: ethcore_miner::pool::queue::TransactionQueue::import
   9: ethcore::client::client::IoChannelQueue::queue::{{closure}}
  10: <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message
  11: ethcore_io::worker::Worker::new::{{closure}}::{{closure}}
  12: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: core::ops::function::FnOnce::call_once{{vtable.shim}}
  15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:87
  16: start_thread
  17: __clone


Thread 'IO Worker #2' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', ethcore/src/client/traits.rs:93
```

**Comment by rakita** [comment]
Duplicate for #69, fix is created here: https://github.com/openethereum/openethereum/pull/149
you will probably need to resync again.
