### ISSUE TITLE
[crash] "Thread 'IO Worker #0' panicked at 'attempted to leave type `linked_hash_map::Node<ethereum_types::H512, (node_table::NodeEndpoint, std::time::Instant)>` uninitialized, which is invalid'" 

### ISSUE THREAD

**Issue by vytk** [openethereum/openethereum#130]
_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: `OpenEthereum/v3.1.0-stable-94a784bfe-20201106/x86_64-linux-gnu/rustc1.48.0`
- **Operating system**: `Linux 4.15.0-124-generic #127-Ubuntu SMP` (running inside VirtualBox)
- **Installation**:  built from source
- **Fully synchronized**: no
- **Network**: `ethereum`
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

While trying to sync, I consistently get a crash after few minutes or hours. 
stack trace:

```
2020-11-26 14:21:35 UTC Syncing snapshot 106/3827        #0   25/25 peers   1 KiB chain 0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2020-11-26 14:21:40 UTC Syncing snapshot 106/3827        #0   25/25 peers   1 KiB chain 0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2020-11-26 14:21:46 UTC Syncing snapshot 106/3827        #0   25/25 peers   1 KiB chain 0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2020-11-26 14:21:51 UTC Syncing snapshot 106/3827        #0   25/25 peers   1 KiB chain 0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2020-11-26 14:21:52 UTC Panic occured, see stderr for details


====================

stack backtrace:
   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at library/std/src/panicking.rs:581
   2: std::panicking::begin_panic_handler::{{closure}}
             at library/std/src/panicking.rs:484
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at library/std/src/sys_common/backtrace.rs:153
   4: rust_begin_unwind
             at library/std/src/panicking.rs:483
   5: core::panicking::panic_fmt
             at library/core/src/panicking.rs:85
   6: core::panicking::panic
             at library/core/src/panicking.rs:50
   7: linked_hash_map::LinkedHashMap<K,V,S>::insert
   8: lru_cache::LruCache<K,V,S>::insert
   9: ethcore_network_devp2p::discovery::Discovery::on_packet
  10: <ethcore_network_devp2p::host::Host as ethcore_io::IoHandler<ethcore_network::NetworkIoMessage>>::stream_readable
  11: ethcore_io::worker::Worker::new::{{closure}}::{{closure}}
  12: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: core::ops::function::FnOnce::call_once{{vtable.shim}}
  15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
      std::sys::unix::thread::Thread::new::thread_start
             at library/std/src/sys/unix/thread.rs:87
  16: start_thread
  17: __clone


Thread 'IO Worker #0' panicked at 'attempted to leave type `linked_hash_map::Node<ethereum_types::H512, (node_table::NodeEndpoint, std::time::Instant)>` uninitialized, which is invalid', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/mem/mod.rs:658

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new
2020-11-26 14:21:52 UTC Finishing work, please wait...
Error: 1
```

 **steps to reproduce**
None in particular. Simply trying to run the client and perform the initial sync will always result in this type of crash after a few minutes or hours. The delay between launch and crash varies wildly.

**Comment by roninkaizen** [comment]
/rustc1.48.0-
if you tried with 
**rustup override set 1.46.0** 
before compiling? 
that could help, please report back, if it solved your issue

**Comment by roninkaizen** [comment]
double of #120

**Comment by vytk** [comment]
PS: Alright, will try again with `rustup override set 1.46.0`. Hopefully that solves it. Thanks.
