### ISSUE TITLE
panicked at 'attempted to leave type … uninitialized, which is invalid'

### ISSUE THREAD

**Issue by colourful-land** [openethereum/openethereum#137]
Exact error is  `linked_hash_map::Node<ethereum_types::H512, (node_table::NodeEndpoint, std::time::Instant)>`  as you can see from the following screen transcript.

- **OpenEthereum version (>=3.1.0)**: v3.10
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

````
$ openethereum/target/release/openethereum --mode=active  -d /var/local/openethereum/ --ports-shift=1024
…
2020-11-30 13:41:23 UTC Syncing snapshot 43/5706        #0   18/25 peers   1 KiB chain 0 bytes queue  RPC:  0 conn,    0 req/s,   11 µs
2020-11-30 13:41:24 UTC Panic occured, see stderr for details


====================

stack backtrace:
   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at library/std/src/panicking.rs:581
   2: std::panicking::begin_panic_handler::{{closure}}
             at library/std/src/panicking.rs:484
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at library/std/src/sys_common/backtrace.rs:153
   4: rust_begin_unwind
             at library/std/src/panicking.rs:483
   5: core::panicking::panic_fmt
             at library/core/src/panicking.rs:85
   6: core::panicking::panic
             at library/core/src/panicking.rs:50
   7: linked_hash_map::LinkedHashMap<K,V,S>::insert
   8: lru_cache::LruCache<K,V,S>::insert
   9: ethcore_network_devp2p::discovery::Discovery::on_packet
  10: <ethcore_network_devp2p::host::Host as ethcore_io::IoHandler<ethcore_network::NetworkIoMessage>>::stream_readable
  11: ethcore_io::worker::Worker::new::{{closure}}::{{closure}}
  12: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: core::ops::function::FnOnce::call_once{{vtable.shim}}
  15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
      std::sys::unix::thread::Thread::new::thread_start
             at library/std/src/sys/unix/thread.rs:87
  16: start_thread
  17: __clone


Thread 'IO Worker #1' panicked at 'attempted to leave type `linked_hash_map::Node<ethereum_types::H512, (node_table::NodeEndpoint, std::time::Instant)>` uninitialized, which is invalid', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/mem/mod.rs:658

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


````

**Comment by roninkaizen** [comment]
builded with rust 1.4.8 as it seems to me?
try rustup override set 1.46.0
before trying to recompile or use the /dev branch :)

**Comment by colourful-land** [comment]
> builded with rust 1.4.8 as it seems to me?

Nope.
````
$ rustc  --version
rustc 1.48.0 (7eac88abb 2020-11-16)
````

> before trying to recompile or use the /dev branch :)

Nope. Using the v3.1.0 tag, not the master branch or any developer's branch.

**Comment by rakita** [comment]
There was a problem with rust `1.48`, downgrade to `1.47` if you want to build `v3.1.0` tag. Fix for new rust version is in `dev` branch.

**Comment by colourful-land** [comment]
Okay I'll close it for now.
