### ISSUE TITLE
Thread 'Verifier #0' panicked then Thread 'event.loop0' panicked

### ISSUE THREAD

**Issue by colourful-land** [openethereum/openethereum#139]
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: v3.1.0
- **Operating system**: Linux
- **Installation**: built from source (v3.1.0, not master)
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: no, this is the first run

The command:

````
$ openethereum/target/release/openethereum --mode=active  -d /var/local/openethereum/ --ports-shift=1024 --chain=ethereum --reserved-peers=reserved_peer --no-warp
````

Following output says I should restart and it will attempt a repair. I restarted, only to see another error.

````

2020-12-01 06:29:08 UTC Syncing #1153208 0xf750…e855    38.35 blk/s  381.1 tx/s   10.2 Mgas/s  13556+    0 Qed  #1166765   36/50 peers   8 MiB chain 58 MiB queue  RPC:  0 conn,    0 req/s,   10 µs
2020-12-01 06:29:13 UTC Syncing #1153444 0x1750…2bf6    47.18 blk/s  305.3 tx/s    9.6 Mgas/s  13321+    0 Qed  #1166765   36/50 peers   8 MiB chain 57 MiB queue  RPC:  0 conn,    0 req/s,   10 µs
2020-12-01 06:29:15 UTC DB corrupted: Corruption: block checksum mismatch: expected 2168896493, got 3027954451  in /var/local/openethereum//chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/032612.sst offset 44531601 size 16340. Repair will be triggered on next restart
2020-12-01 06:29:16 UTC Panic occured, see stderr for details


====================

stack backtrace:
   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:530
   2: rust_begin_unwind
             at src/libstd/panicking.rs:437
   3: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   4: core::option::expect_none_failed
             at src/libcore/option.rs:1269
   5: ethcore::client::client::Importer::import_verified_blocks
   6: <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message
   7: ethcore_io::service_mio::IoChannel<Message>::send_sync
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:87
  11: start_thread
  12: __clone


Thread 'Verifier #0' panicked at 'DB flush failed.: Custom { kind: Other, error: "Corruption: block checksum mismatch: expected 2168896493, got 3027954451  in /var/local/openethereum//chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/032612.sst offset 44531601 size 16340" }', ethcore/src/client/client.rs:391

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2020-12-01 06:29:16 UTC Finishing work, please wait...
2020-12-01 06:29:16 UTC DB corrupted: Corruption: block checksum mismatch: expected 2168896493, got 3027954451  in /var/local/openethereum//chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/032612.sst offset 44531601 size 16340. Repair will be triggered on next restart
2020-12-01 06:29:16 UTC DB corrupted: Corruption: block checksum mismatch: expected 2168896493, got 3027954451  in /var/local/openethereum//chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/032612.sst offset 44531601 size 16340. Repair will be triggered on next restart
2020-12-01 06:29:17 UTC Panic occured, see stderr for details


====================

stack backtrace:
   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:530
   2: rust_begin_unwind
             at src/libstd/panicking.rs:437
   3: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   4: core::option::expect_none_failed
             at src/libcore/option.rs:1269
   5: <ethcore::verification::queue::VerificationQueue<K> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place
   7: core::ptr::drop_in_place
   8: alloc::sync::Arc<T>::drop_slow
   9: alloc::sync::Arc<T>::drop_slow
  10: alloc::sync::Arc<T>::drop_slow
  11: alloc::sync::Arc<T>::drop_slow
  12: <hashbrown::raw::RawTable<T> as core::ops::drop::Drop>::drop
  13: alloc::sync::Arc<T>::drop_slow
  14: core::ptr::drop_in_place
  15: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  16: tokio_threadpool::worker::Worker::run_task
  17: tokio_threadpool::worker::Worker::run
  18: tokio_reactor::with_default
  19: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  20: std::sys_common::backtrace::__rust_begin_short_backtrace
  21: core::ops::function::FnOnce::call_once{{vtable.shim}}
  22: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:87
  23: start_thread
  24: __clone


Thread 'event.loop0' panicked at 'Propagating verifier thread panic on shutdown: Any', /home/geth/openethereum/ethcore/src/verification/queue/mod.rs:853

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


Error: 1
````

After restarting, the error was:
````
$ openethereum/target/release/openethereum --mode=active  -d /var/local/openethereum/ --ports-shift=1024 --chain=ethereum --reserved-peers=reserved_peer --no-warp --cache-size=16384
2020-12-01 11:40:17 UTC Starting OpenEthereum/v3.1.0-stable-94a784bfe-20201106/x86_64-linux-gnu/rustc1.46.0
2020-12-01 11:40:17 UTC Keys path /var/local/openethereum//keys/ethereum
2020-12-01 11:40:17 UTC DB path /var/local/openethereum//chains/ethereum/db/906a34e69aec8c0d
2020-12-01 11:40:17 UTC State DB configuration: fast
2020-12-01 11:40:17 UTC Operating mode: active
2020-12-01 11:40:17 UTC DB has been previously marked as corrupted, attempting repair
2020-12-01 11:41:20 UTC DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col6, col4, col1, col2, col0, col3, attempting repair
Failed to open database Custom { kind: Other, error: "Received null column family handle from DB." }
Error: 1
````

**Comment by rakita** [comment]
It seems that your data on the hard drive got corrupted, this is an error from rocksdb.
