### ISSUE TITLE
Supplied instant is later than self

### ISSUE THREAD

**Issue by rakita** [openethereum/openethereum#169]
- **OpenEthereum version**: v3.1.0 (probably this: 837e8b8725b87914ff43335d907411ad4c2a4669)
- **Operating system**: linux
- **Installation**: built from source
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

After client get synced to highest block and after ancient blocks start to download, client crashes with this msg:
```
eth1_1    | 2020-12-11 17:44:44 UTC Syncing #11432790 0x0589…bbd0     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+  252 Qed (Ancient:#5397346) LI:#11433033   48/50 peers      5 MiB chain   40 MiB queue  RPC:  0 conn,    2 req/s,  117 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b     0.01 blk/s    1.6 tx/s    0.1 Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b     0.01 blk/s    1.6 tx/s    0.1 Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers    0 bytes chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b      NaN blk/s    NaN tx/s    NaN Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b      NaN blk/s    NaN tx/s    NaN Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b      NaN blk/s    NaN tx/s    NaN Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b      NaN blk/s    NaN tx/s    NaN Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b      NaN blk/s    NaN tx/s    NaN Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Panic occured, see stderr for details
eth1_1    |
eth1_1    |
eth1_1    | ====================
eth1_1    |
eth1_1    | stack backtrace:
eth1_1    |    0: <unknown>
eth1_1    |    1: <unknown>
eth1_1    |    2: <unknown>
eth1_1    |    3: <unknown>
eth1_1    |    4: <unknown>
eth1_1    |    5: <unknown>
eth1_1    |    6: <unknown>
eth1_1    |    7: <unknown>
eth1_1    |    8: <unknown>
eth1_1    |    9: <unknown>
eth1_1    |   10: <unknown>
eth1_1    |   11: <unknown>
eth1_1    |   12: <unknown>
eth1_1    |   13: <unknown>
eth1_1    |
eth1_1    |
eth1_1    | Thread 'IO Worker #1' panicked at 'supplied instant is later than self', library/std/src/time.rs:271
eth1_1    |
eth1_1    | This is a bug. Please report it at:
eth1_1    |
eth1_1    |     https://github.com/openethereum/openethereum/issues/new
eth1_1    |
eth1_1    |
eth1_1    | 2020-12-11 17:47:08 UTC Finishing work, please wait...
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b      NaN blk/s    NaN tx/s    NaN Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b      NaN blk/s    NaN tx/s    NaN Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b      NaN blk/s    NaN tx/s    NaN Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b      NaN blk/s    NaN tx/s    NaN Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b      NaN blk/s    NaN tx/s    NaN Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b      NaN blk/s    NaN tx/s    NaN Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b      NaN blk/s    NaN tx/s    NaN Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b      NaN blk/s    NaN tx/s    NaN Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b      NaN blk/s    NaN tx/s    NaN Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b      NaN blk/s    NaN tx/s    NaN Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | 2020-12-11 17:47:08 UTC Syncing #11432791 0x0c31…640b      NaN blk/s    NaN tx/s    NaN Mgas/s      0+  260 Qed (Ancient:#5402621) LI:#11433041   51/50 peers     72 KiB chain   41 MiB queue  RPC:  0 conn,    0 req/s,   82 µs
eth1_1    | Error: 1
```

After restart, same issue is reported.
After setting a larger cache size it seems to help.

**Comment by rakita** [comment]
@yorickdowne can you try this: https://github.com/rakita/openethereum/tree/instant_hunch

**Comment by yorickdowne** [comment]
Shall do.

**Comment by yorickdowne** [comment]
Okay great, one of the test machines crashed: "Thread 'Worker Client2' panicked at 'We got the bug.', parity/informant.rs:229"

**Comment by rakita** [comment]
Sweet, I was afraid that it is somewhere else but it seems that we found where it is.

**Comment by yorickdowne** [comment]
PR #193 did not work well for me. On an OE that has been fully synced and has all ancient blocks, it imported a few blocks and then stopped outputting logs, with no movement in 9 hours.

```
yorick@ethlinux:~/oe-main$ date
Thu 07 Jan 2021 01:57:19 PM EST
yorick@ethlinux:~/oe-main$ docker-compose logs -f eth1
Attaching to oe-main_eth1_1
eth1_1    | 2021-01-07 18:19:19 UTC Starting OpenEthereum/v3.1.0-rc1-stable-64453303b-20210104/x86_64-linux-musl/rustc1.47.0
eth1_1    | 2021-01-07 18:19:19 UTC Keys path /var/lib/openethereum/keys/ethereum
eth1_1    | 2021-01-07 18:19:19 UTC DB path /var/lib/openethereum/chains/ethereum/db/906a34e69aec8c0d
eth1_1    | 2021-01-07 18:19:19 UTC State DB configuration: fast
eth1_1    | 2021-01-07 18:19:19 UTC Operating mode: active
eth1_1    | 2021-01-07 18:19:19 UTC Configured for Ethereum using Ethash engine
eth1_1    | 2021-01-07 18:19:21 UTC Listening for new connections on 0.0.0.0:8546.
eth1_1    | 2021-01-07 18:19:22 UTC Updated conversion rate to Ξ1 = US$1285.05 (3705618 wei/gas)
eth1_1    | 2021-01-07 18:19:27 UTC Public node URL: enode://673e0a700c46e5f83d17e3b82786a6fdba0e034f18e832ea19974229a258d9b7c142ee963cf108b0694583051bf9a3b4f1f3bafbf3ab11a38a30500694f42de5@172.21.0.2:30303
eth1_1    | 2021-01-07 18:19:40 UTC Imported #11609135 0x8c6a…ebb8 (194 txs, 12.42 Mgas, 3288 ms, 57.16 KiB)
eth1_1    | 2021-01-07 18:19:47 UTC Imported #11609136 0xc60f…38b4 (157 txs, 12.41 Mgas, 1682 ms, 52.80 KiB)
eth1_1    | 2021-01-07 18:19:56 UTC Imported #11609137 0xd6bc…1262 (179 txs, 12.38 Mgas, 2251 ms, 55.82 KiB)
eth1_1    | 2021-01-07 18:20:11 UTC Imported #11609139 0xc34a…613d (173 txs, 12.43 Mgas, 1056 ms, 32.25 KiB)
eth1_1    | 2021-01-07 18:20:16 UTC Imported #11609140 0x8954…e36f (140 txs, 12.44 Mgas, 1280 ms, 47.21 KiB)
eth1_1    | 2021-01-07 18:20:23 UTC Imported #11609141 0x4780…d4a0 (281 txs, 12.36 Mgas, 1831 ms, 51.05 KiB)
eth1_1    | 2021-01-07 18:20:36 UTC Imported #11609142 0x2a1a…dee6 (149 txs, 12.42 Mgas, 1104 ms, 38.72 KiB)
eth1_1    | 2021-01-07 18:20:51 UTC Imported #11609143 0x64ee…734d (161 txs, 12.44 Mgas, 730 ms, 38.46 KiB)
eth1_1    | 2021-01-07 18:21:24 UTC Imported #11609144 0x514c…50b5 (168 txs, 12.45 Mgas, 1289 ms, 50.96 KiB)
eth1_1    | 2021-01-07 18:21:26 UTC Imported #11609145 0x39a6…5ac6 (149 txs, 12.47 Mgas, 1006 ms, 46.25 KiB)
^CERROR: Aborting.
yorick@ethlinux:~/oe-main$ date
Thu 07 Jan 2021 10:07:33 PM EST
```

**Comment by rakita** [comment]
Yes, I can see why it didnt work, I didnt put proper scope on read mutex and it deadlocks because of multiple concurrent read->write on same lock. It is fixed now, and thank you.
