### ISSUE TITLE
Thread 'IO Worker #0' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', ethcore/src/client/traits.rs:93

### ISSUE THREAD

**Issue by darzyx** [openethereum/openethereum#207]
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: 3.1.0
- **Operating system**: Linux
- **Installation**: binaries
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Expected behavior: running normally after sync

Actual behavior: crashes and gives the following error and instructs me to report it here as a bug.

`Thread 'IO Worker #0' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', ethcore/src/client/traits.rs:93
`

Restarting starts syncing again, but eventually, it crashes again within the hour.

**Comment by darzyx** [comment]
Closing since this is a repeat of #171
