### ISSUE TITLE
Thread 'IO Worker #0' panicked at 'attempted to leave type `linked_hash_map::Node<ethereum_types::H512, (node_table::NodeEndpoint, std::time::Instant)>` uninitialized, which is invalid'

### ISSUE THREAD

**Issue by artyukh** [openethereum/openethereum#239]
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version**: v3.0.0-stable
- **Operating system**:  Linux
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: ethereum 
- **Restarted**: yes
**rustc 1.49.0**

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

FULL ERROR

   0: panic_hook::gen_panic_msg
   1: panic_hook::set_with::{{closure}}
   2: std::panicking::rust_panic_with_hook
             at library/std/src/panicking.rs:597
   3: std::panicking::begin_panic_handler::{{closure}}
             at library/std/src/panicking.rs:497
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at library/std/src/sys_common/backtrace.rs:141
   5: rust_begin_unwind
             at library/std/src/panicking.rs:495
   6: core::panicking::panic_fmt
             at library/core/src/panicking.rs:92
   7: core::panicking::panic
             at library/core/src/panicking.rs:50
   8: linked_hash_map::LinkedHashMap<K,V,S>::insert
   9: lru_cache::LruCache<K,V,S>::insert
  10: ethcore_network_devp2p::discovery::Discovery::on_packet
  11: <ethcore_network_devp2p::host::Host as ethcore_io::IoHandler<ethcore_network::NetworkIoMessage>>::stream_readable
  12: ethcore_io::worker::Worker::new::{{closure}}::{{closure}}
  13: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
  14: std::sys_common::backtrace::__rust_begin_short_backtrace
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
  16: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307
      std::sys::unix::thread::Thread::new::thread_start
             at library/std/src/sys/unix/thread.rs:71
  17: start_thread
  18: clone

Thread 'IO Worker #0' panicked at 'attempted to leave type `linked_hash_map::Node<ethereum_types::H512, (node_table::NodeEndpoint, std::time::Instant)>` uninitialized, which is invalid', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/mem/mod.rs:659

**Comment by artyukh** [comment]
![image](https://user-images.githubusercontent.com/29544129/105746076-0c1a3a80-5f50-11eb-9210-c792bb6aedf5.png)

**Comment by artyukh** [comment]
![image](https://user-images.githubusercontent.com/29544129/105746459-821ea180-5f50-11eb-9274-338d334c517b.png)

Started as 
openethereum  --config /etc/parity/config.toml

/etc/parity/config.toml
[parity]
base_path = "/chain_data/eth"
identity = ""
mode="active"
no_persistent_txqueue = true


[misc]
logging = "own_tx=trace"
log_file = "/var/log/parity.log"
color = true

[footprint]
tracing = "off"
db_compaction = "ssd"
pruning = "fast"
cache_size = 40960

**Comment by artyukh** [comment]
Fixed by cargo update -p linked-hash-map
