### ISSUE TITLE
panic: there is no such thing as a release failure ordering

### ISSUE THREAD

**Issue by q9f** [openethereum/openethereum#312]
- **OpenEthereum version (>=3.1.0)**: v3.2.0-rc.1-stable-e2024c4b8-20210310/x86_64-linux-gnu/rustc1.50.0 (dev)
- **Operating system**: ArchLinux
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: zosma (dm on discord for chain spec)
- **Restarted**: yes

```
~/.opt/openethereum/openethereum dev
❯ target/release/openethereum --chain ~/Desktop/zosma-v4.json --ports-shift 4567 -d /tmp/zosma
2021-03-10 10:25:11  Starting OpenEthereum/v3.2.0-rc.1-stable-e2024c4b8-20210310/x86_64-linux-gnu/rustc1.50.0
2021-03-10 10:25:11  Keys path /tmp/zosma/keys/zosma-4
2021-03-10 10:25:11  DB path /tmp/zosma/chains/zosma-4/db/625cc4eeb1b927e2
2021-03-10 10:25:11  State DB configuration: fast
2021-03-10 10:25:11  Operating mode: active
2021-03-10 10:25:11  Configured for Zosma (v4) using AuthorityRound engine
2021-03-10 10:25:12  Listening for new connections on 127.0.0.1:13113.
2021-03-10 10:25:12  Public node URL: enode://d26e57c62398d3d55e0a80386fac4f975717f3ba23479ed06d3baef757e1790073b11e988ca33780acc6c22260ffcc7d028c3eac54b13ccaa2ab4bb766d9a99b@192.168.1.100:34870
2021-03-10 10:25:12  Panic occured, see stderr for details


====================

stack backtrace:
   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b//library/std/src/panicking.rs:595
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b//library/std/src/panicking.rs:495
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b//library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b//library/std/src/panicking.rs:493
   5: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b//library/core/src/panicking.rs:92
   6: core::panicking::panic
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b//library/core/src/panicking.rs:50
   7: core::sync::atomic::atomic_compare_exchange
   8: core::sync::atomic::AtomicBool::compare_exchange
   9: <ethcore_sync::api::SyncProtocolHandler as ethcore_network::NetworkProtocolHandler>::timeout
  10: <ethcore_network_devp2p::host::Host as ethcore_io::IoHandler<ethcore_network::NetworkIoMessage>>::timeout
  11: ethcore_io::worker::Worker::new::{{closure}}::{{closure}}
  12: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: core::ops::function::FnOnce::call_once{{vtable.shim}}
  15: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/boxed.rs:1328
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/boxed.rs:1328
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b//library/std/src/sys/unix/thread.rs:71
  16: start_thread
  17: __GI___clone


Thread 'Worker devp2p3' panicked at 'there is no such thing as a release failure ordering', /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/sync/atomic.rs:2547

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2021-03-10 10:25:12  Finishing work, please wait...
Error: 1
```

**Comment by q9f** [comment]
Just to confirm, I also get this on other networks, e.g., Goerli Testnet:

```
~/.opt/openethereum/openethereum dev
❯ target/release/openethereum --chain goerli --ports-shift 4567 -d /tmp/goerli
2021-03-10 10:29:04  Starting OpenEthereum/v3.2.0-rc.1-stable-e2024c4b8-20210310/x86_64-linux-gnu/rustc1.50.0
2021-03-10 10:29:04  Keys path /tmp/goerli/keys/goerli
2021-03-10 10:29:04  DB path /tmp/goerli/chains/goerli/db/b1d518969eab529d
2021-03-10 10:29:04  State DB configuration: fast
2021-03-10 10:29:04  Operating mode: active
2021-03-10 10:29:04  Configured for Görli Testnet using Clique engine
2021-03-10 10:29:04  Listening for new connections on 127.0.0.1:13113.
2021-03-10 10:29:04  Public node URL: enode://b2b75e695c263ca5977ad865e5406456de5a173069b3ec754e818c693557f9f8914528f5a4b24b03c40ce5a16dab5ba4fa8e938a757c822ea60beeaab7114412@192.168.1.100:34870
2021-03-10 10:29:05  Panic occured, see stderr for details


====================

stack backtrace:
   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b//library/std/src/panicking.rs:595
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b//library/std/src/panicking.rs:495
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b//library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b//library/std/src/panicking.rs:493
   5: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b//library/core/src/panicking.rs:92
   6: core::panicking::panic
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b//library/core/src/panicking.rs:50
   7: core::sync::atomic::atomic_compare_exchange
   8: core::sync::atomic::AtomicBool::compare_exchange
   9: <ethcore_sync::api::SyncProtocolHandler as ethcore_network::NetworkProtocolHandler>::timeout
  10: <ethcore_network_devp2p::host::Host as ethcore_io::IoHandler<ethcore_network::NetworkIoMessage>>::timeout
  11: ethcore_io::worker::Worker::new::{{closure}}::{{closure}}
  12: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: core::ops::function::FnOnce::call_once{{vtable.shim}}
  15: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/boxed.rs:1328
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/boxed.rs:1328
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b//library/std/src/sys/unix/thread.rs:71
  16: start_thread
  17: __GI___clone


Thread 'Worker devp2p2' panicked at 'there is no such thing as a release failure ordering', /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/sync/atomic.rs:2547

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2021-03-10 10:29:05  Finishing work, please wait...
Error: 1
```

**Comment by rakita** [comment]
You are fast, It is because of the last commit on dev, merged 1h ago.

**Comment by roninkaizen** [comment]
good morning!

**Comment by rakita** [comment]
Thank you.
pushed fix here: https://github.com/openethereum/openethereum/pull/306
and will merge it after github actions finish.

**Comment by rakita** [comment]
Fix merged
