### ISSUE TITLE
openethereum panicked and won't start

### ISSUE THREAD

**Issue by dimaa6** [openethereum/openethereum#421]
openethereum[6242]: 0: panic_hook::set_with::{{closure}}
openethereum[6242]: 1: std::panicking::rust_panic_with_hook
openethereum[6242]: at rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:595:17
openethereum[6242]: 2: std::panicking::begin_panic_handler::{{closure}}
openethereum[6242]: at rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:497:13
openethereum[6242]: 3: std::sys_common::backtrace::__rust_end_short_backtrace
openethereum[6242]: at rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:141:18
openethereum[6242]: 4: rust_begin_unwind
openethereum[6242]: at rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
openethereum[6242]: 5: core::panicking::panic_fmt
openethereum[6242]: at rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
openethereum[6242]: 6: core::option::expect_none_failed
openethereum[6242]: at rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
openethereum[6242]: 7: ethcore::trace::db::TraceDB<T>::traces
openethereum[6242]: 8: <ethcore::client::client::Client as ethcore::client::traits::BlockChainClient>::transaction_traces
openethereum[6242]: 9: <jsonrpc_core::delegates::DelegateAsyncMethod<T,F> as jsonrpc_core::calls::RpcMethod<M>>::call
openethereum[6242]: 10: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
openethereum[6242]: 11: <futures::future::map::Map<A,F> as futures::future::Future>::poll
openethereum[6242]: 12: <futures::future::map::Map<A,F> as futures::future::Future>::poll
openethereum[6242]: 13: <jsonrpc_http_server::handler::RpcHandler<M,S> as futures::future::Future>::poll
openethereum[6242]: 14: <jsonrpc_http_server::handler::RpcHandler<M,S> as futures::future::Future>::poll
openethereum[6242]: 15: <jsonrpc_http_server::handler::RpcHandler<M,S> as futures::future::Future>::poll
openethereum[6242]: 16: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
openethereum[6242]: 17: futures::future::option::<impl futures::future::Future for core::option::Option<F>>::poll
openethereum[6242]: 18: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
openethereum[6242]: 19: tokio_threadpool::worker::Worker::run_task
openethereum[6242]: 20: tokio_threadpool::worker::Worker::run
openethereum[6242]: 21: tokio_reactor::with_default
openethereum[6242]: 22: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
openethereum[6242]: 23: std::sys_common::backtrace::__rust_begin_short_backtrace
openethereum[6242]: 24: core::ops::function::FnOnce::call_once{{vtable.shim}}
openethereum[6242]: 25: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
openethereum[6242]: at rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/boxed.rs:1328:9
openethereum[6242]: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
openethereum[6242]: at rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/boxed.rs:1328:9
openethereum[6242]: std::sys::unix::thread::Thread::new::thread_start
openethereum[6242]: at rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys/unix/thread.rs:71:17
openethereum[6242]: 26: start_thread
openethereum[6242]: 27: __clone
openethereum[6242]: Thread 'http.worker630' panicked at 'decode db value failed: RlpExpectedToBeData', parity3/crates/db/db/src/db.rs:295
openethereum[6242]: This is a bug. Please report it at:
openethereum[6242]: https://github.com/openethereum/openethereum/issues/new
openethereum[6242]: 2021-05-28 07:46:09 UTC Panic occured, see stderr for details

**Comment by yorickdowne** [comment]
That sounds like DB corruption. Definitely rule out hardware issues

- Memtest86 for 4-5 days unless this is ECC, in which case check ECC error logs for uncorrected errors
- If ZFS check scrub; if not ZFS look at SMART to see whether there's any indication of storage failure
