### ISSUE TITLE
Rolling back blocks with db reset leads to failures starting 3.3.0-rc2

### ISSUE THREAD

**Issue by Asara** [openethereum/openethereum#462]
I am running `openethereum --config /etc/parity/parity.toml db reset 64` to reset my block state to do some testing.  This works with openethereum 3.2.3, where the client will just start syncing up to tip again.  With 3.3.0-rc2 I get the following error:

```
====================
   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   6: core::option::expect_failed
             at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1292:5
   7: parity_rpc::v1::impls::eth::EthClient<C,SN,S,M,EM>::rich_block
   8: <jsonrpc_core::delegates::DelegateAsyncMethod<T,F> as jsonrpc_core::calls::RpcMethod<M>>::call
   9: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  10: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  11: <jsonrpc_http_server::handler::RpcHandler<M,S> as futures::future::Future>::poll
  12: <jsonrpc_http_server::handler::RpcHandler<M,S> as futures::future::Future>::poll
  13: <jsonrpc_http_server::handler::RpcHandler<M,S> as futures::future::Future>::poll
  14: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
  15: futures::future::option::<impl futures::future::Future for core::option::Option<F>>::poll
  16: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  17: tokio_threadpool::worker::Worker::run_task
  18: tokio_threadpool::worker::Worker::run
  19: tokio_reactor::with_default
  20: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  21: std::sys_common::backtrace::__rust_begin_short_backtrace
  22: core::ops::function::FnOnce::call_once{{vtable.shim}}
  23: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  24: start_thread
  25: clone
Thread 'http.worker00' panicked at 'Object exists in blockchain (fetched earlier), extra_info is always available if object exists; qed', /tmp/openethereum/crates/rpc/src/v1/impls/eth.rs:316
```

**Comment by SomethingUseful** [comment]
same with 3.3.0-rc4 ... "db reset"
main INFO ethcore_service::service  Configured for Ropsten Testnet using Ethash engine
Attempting to reset to block with pruned state
Error: 1
