### ISSUE TITLE
ERROR: thread 'main' panicked at 'block header, view rlp is trusted and should be valid: RlpIsTooBig'

### ISSUE THREAD

**Issue by cy92830** [openethereum/openethereum#513]
- **OpenEthereum version (>=3.1.0)**: 3.3.0-rc.6
- **Operating system**: Linux
- **Installation**: github release
- **Fully synchronized**: yes
- **Network**: kovan
- **Restarted**: yes

Error occurs:

2021-08-23 16:48:09  Configured for Kovan Testnet using AuthorityRound engine
thread 'main' panicked at 'block header, view rlp is trusted and should be valid: RlpIsTooBig', crates/ethcore/types/src/encoded.rs:290:17
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

After setting RUST_BACKTRACE=full, Error occurs:

2021-08-23 16:48:25  Configured for Kovan Testnet using AuthorityRound engine
thread 'main' panicked at 'block header, view rlp is trusted and should be valid: RlpIsTooBig', crates/ethcore/types/src/encoded.rs:290:17
stack backtrace:
   0:     0x55df4c860b00 - <unknown>
   1:     0x55df4bb3719f - <unknown>
   2:     0x55df4c8603e1 - <unknown>
   3:     0x55df4c85fd85 - <unknown>
   4:     0x55df4c85f178 - <unknown>
   5:     0x55df4c87cc18 - <unknown>
   6:     0x55df4c87cb8c - <unknown>
   7:     0x55df4c87cb3d - <unknown>
   8:     0x55df4b9b6bb0 - <unknown>
   9:     0x55df4bb25fa7 - <unknown>
  10:     0x55df4be59890 - <unknown>
  11:     0x55df4bd076e6 - <unknown>
  12:     0x55df4bf0172b - <unknown>
  13:     0x55df4c4cb509 - <unknown>
  14:     0x55df4c53c798 - <unknown>
  15:     0x55df4c5d8713 - <unknown>
  16:     0x55df4c5d32b3 - <unknown>
  17:     0x55df4c5d5156 - <unknown>
  18:     0x7f3b434a97b3 - __libc_start_main
  19:     0x55df4ba84549 - <unknown>
  20:                0x0 - <unknown>

**Comment by cy92830** [comment]
Downgrade to 3.3.0-rc.4 works well

**Comment by poseidon-j** [comment]
Yes I got this same error.. and I downgraded to rc4
