### ISSUE TITLE
openethereum-v3.3.0-rc.15 crashed and not start

### ISSUE THREAD

**Issue by chakhalyan1** [openethereum/openethereum#574]
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: v3.3.0-rc.15
- **Operating system**: Linux
- **Installation**: homebrew
- **Fully synchronized**: yes
- **Network**: ethereum 
- **Restarted**:  yes

our etherum node synced ad working well, I have update every your realise, today it was stoped and did not starting. 
I have attached etherum log when I want start 
`2021-11-23 10:27:24 UTC Starting OpenEthereum/v3.3.0-rc.15-stable-88eb7d325-20211104/x86_64-linux-gnu/rustc1.48.0
2021-11-23 10:27:24 UTC Keys path /root/.local/share/openethereum/keys/ethereum
2021-11-23 10:27:24 UTC DB path /root/.local/share/openethereum/chains/ethereum/db/906a34e69aec8c0d
2021-11-23 10:27:24 UTC State DB configuration: fast
2021-11-23 10:27:24 UTC Operating mode: active
2021-11-23 10:27:24 UTC Configured for Ethereum using Ethash engine
2021-11-23 10:27:26 UTC Listening for new connections on 127.0.0.1:8546.
2021-11-23 10:27:26 UTC Updated conversion rate to Ξ1 = US$4220.21 (1128357.3 wei/gas)
2021-11-23 10:27:28 UTC Panic occured, see stderr for details

====================

   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:581:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484:9
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153:18
   4: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483:5
   5: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85:14
   6: core::option::expect_none_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234:5
   7: <journaldb::overlayrecentdb::OverlayRecentDB as hash_db::HashDB<keccak_hasher::KeccakHasher,elastic_array::ElasticArray128<u8>>>::get
   8: <ethcore::account_db::AccountDB as hash_db::HashDB<keccak_hasher::KeccakHasher,elastic_array::ElasticArray128<u8>>>::get
   9: <&mut dyn hash_db::HashDB<H,T> as hash_db::HashDBRef<H,T>>::get
  10: ethcore::state::account::Account::get_and_cache_storage
  11: ethcore::state::State<B>::storage_at
  12: <ethcore::externalities::Externalities<T,V,B> as vm::ext::Ext>::storage_at
  13: evm::interpreter::Interpreter<Cost>::exec_instruction
  14: <evm::interpreter::Interpreter<Cost> as vm::Exec>::exec
  15: ethcore::executive::CallCreateExecutive::exec
  16: ethcore::executive::CallCreateExecutive::consume
  17: ethcore::executive::Executive<B>::call_with_stack_depth
  18: ethcore::executive::Executive<B>::transact
  19: ethcore::block::OpenBlock::push_transaction
  20: ethcore::client::client::Importer::import_verified_blocks
  21: <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message
  22: ethcore_io::service_mio::IoChannel<Message>::send_sync
  23: std::sys_common::backtrace::__rust_begin_short_backtrace
  24: core::ops::function::FnOnce::call_once{{vtable.shim}}
  25: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042:9
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/unix/thread.rs:87:17
  26: start_thread
  27: __clone

Thread 'Verifier #0' panicked at 'Low-level database error. Some issue with your hard disk?: Custom { kind: Other, error: "Corruption: Snappy not supported or corrupted Snappy compressed block contents" }', crates/db/journaldb/src/overlayrecentdb.rs:180

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new

2021-11-23 10:27:28 UTC Finishing work, please wait...
2021-11-23 10:27:31 UTC Panic occured, see stderr for details

====================

   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:581:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484:9
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153:18
   4: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483:5
   5: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85:14
   6: core::option::expect_none_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234:5
   7: <ethcore::verification::queue::VerificationQueue<K> as core::ops::drop::Drop>::drop
   8: core::ptr::drop_in_place
   9: core::ptr::drop_in_place.30458
  10: alloc::sync::Arc<T>::drop_slow
  11: alloc::sync::Arc<T>::drop_slow
  12: alloc::sync::Arc<T>::drop_slow
  13: core::ptr::drop_in_place
  14: alloc::sync::Arc<T>::drop_slow
  15: alloc::sync::Arc<T>::drop_slow
  16: alloc::sync::Arc<T>::drop_slow
  17: <hashbrown::raw::RawTable<T> as core::ops::drop::Drop>::drop
  18: alloc::sync::Arc<T>::drop_slow
  19: core::ptr::drop_in_place
  20: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  21: tokio_threadpool::worker::Worker::run_task
  22: tokio_threadpool::worker::Worker::run
  23: tokio_reactor::with_default
  24: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  25: std::sys_common::backtrace::__rust_begin_short_backtrace
  26: core::ops::function::FnOnce::call_once{{vtable.shim}}
  27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042:9
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/unix/thread.rs:87:17
  28: start_thread
  29: __clone

Thread 'event.loop0' panicked at 'Propagating verifier thread panic on shutdown: Any', /home/vadim/nethermind-tests/openethereum/crates/ethcore/src/verification/queue/mod.rs:864

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new

Error: 1`

**Comment by varasev** [comment]
@chakhalyan1 please clarify was your disk full before this error occured?

**Comment by roninkaizen2021** [comment]
@varasev any chance to get in contact with you? tried to reach out on other ways, would really like to exchange with you
